export const VOCABULARY_LIST = [
  { word: "Attainment", pos: "Noun", meaning: "Sự đạt được/thành tựu", example: "The attainment of competence.", note: "Từ gốc: attain" },
  { word: "Intervene", pos: "Verb", meaning: "Can thiệp", example: "Developing intervention strategies.", note: "Noun: intervention" },
  { word: "Alleviate", pos: "Verb", meaning: "Làm nhẹ bớt", example: "Alleviating family stress.", note: "Đồng nghĩa: relieve, ease" },
  { word: "Liaison", pos: "Noun", meaning: "Liên lạc/Mối liên kết", example: "School-Community Liaison.", note: "Dễ sai chính tả" },
  { word: "Truancy", pos: "Noun", meaning: "Sự trốn học", example: "Programs for truants.", note: "Truant (người)" },
  { word: "Competence", pos: "Noun", meaning: "Năng lực", example: "Attainment of competence.", note: "Adj: competent" },
  { word: "Facilitate", pos: "Verb", meaning: "Tạo điều kiện", example: "Facilitate support.", note: "Hỗ trợ tiến trình" },
  { word: "Assessment", pos: "Noun", meaning: "Đánh giá", example: "Special Education Assessment.", note: "Verb: assess" },
  { word: "Collaboration", pos: "Noun", meaning: "Hợp tác", example: "Collaboration is key.", note: "Làm việc chung" },
  { word: "Interfere", pos: "Verb", meaning: "Cản trở", example: "Interfere with learning.", note: "Luôn đi với 'with'" },
  { word: "Personnel", pos: "Noun", meaning: "Nhân sự", example: "School Personnel.", note: "Dễ nhầm với Personal" },
  { word: "Mobilize", pos: "Verb", meaning: "Huy động", example: "Mobilizing resources.", note: "Huy động nguồn lực" },
  { word: "Societal", pos: "Adjective", meaning: "Thuộc xã hội", example: "Societal forces.", note: "Từ Society" },
  { word: "Familial", pos: "Adjective", meaning: "Thuộc gia đình", example: "Familial factors.", note: "Từ Family" },
  { word: "Compliance", pos: "Noun", meaning: "Tuân thủ", example: "Compliance with law.", note: "Verb: comply with" },
  { word: "Accommodate", pos: "Verb", meaning: "Đáp ứng/Chứa đựng", example: "The school will accommodate all students.", note: "Chữ cc và mm dễ viết sai." },
  { word: "Implementation", pos: "Noun", meaning: "Sự thi hành/thực hiện", example: "The implementation of the new policy.", note: "Gốc động từ: implement." },
  { word: "Comprehensive", pos: "Adjective", meaning: "Toàn diện", example: "A comprehensive review of the syllabus.", note: "Tuyệt đối không nhầm với 'Comprehend' (hiểu)." },
  { word: "Discrepancy", pos: "Noun", meaning: "Sự chênh lệch/khác biệt", example: "A discrepancy between statements.", note: "Thường dùng mô tả số liệu, lời khai." },
  { word: "Fundamental", pos: "Adjective", meaning: "Cơ bản/Trọng yếu", example: "Fundamental human rights.", note: "Quan trọng hơn 'basic'." },
  { word: "Methodology", pos: "Noun", meaning: "Phương pháp luận", example: "Research methodology in social work.", note: "Hệ thống các phương pháp nghiên cứu." },
  { word: "Integration", pos: "Noun", meaning: "Sự hội nhập/tích hợp", example: "Integration into the mainstream curriculum.", note: "Động từ: integrate." },
  { word: "Theoretical", pos: "Adjective", meaning: "Thuộc về lý thuyết", example: "Theoretical framework guiding the study.", note: "Thường đi kèm với 'framework' hoặc 'approach'." },
  { word: "Consequently", pos: "Adverb", meaning: "Do đó/Hậu quả là", example: "Consequently, the project was delayed.", note: "Giống 'As a result'." },
  { word: "Significance", pos: "Noun", meaning: "Sự quan trọng/Ý nghĩa", example: "The significance of early childhood education.", note: "Tính từ: significant." },
  { word: "Alternative", pos: "Noun/Adjective", meaning: "Sự thay thế/Lựa chọn khác", example: "We need an alternative approach.", note: "Hay gặp trong các bài toán đưa ra giải pháp." },
  { word: "Conventional", pos: "Adjective", meaning: "Theo truyền thống/Lệ thường", example: "Conventional methods of teaching.", note: "Đồng nghĩa: traditional, standard." },
  { word: "Substantial", pos: "Adjective", meaning: "Đáng kể/To lớn", example: "A substantial amount of funding.", note: "Dùng để mô tả số lượng, ảnh hưởng." },
  { word: "Perspective", pos: "Noun", meaning: "Góc nhìn/Quan điểm", example: "From a social worker's perspective.", note: "Đồng nghĩa: viewpoint." },
  { word: "Empowerment", pos: "Noun", meaning: "Sự trao quyền", example: "Focusing on community empowerment.", note: "Rất hay gặp trong ngành Xã hội học." },
  { word: "Marginalized", pos: "Adjective", meaning: "Bị gạt ra ngoài lề (xã hội)", example: "Helping marginalized populations.", note: "Từ khóa cực quan trọng trong Social Work." },
  { word: "Vulnerability", pos: "Noun", meaning: "Sự dễ bị tổn thương", example: "Assessing the client's vulnerability.", note: "Tính từ: vulnerable." },
  { word: "Resilience", pos: "Noun", meaning: "Sự kiên cường/Khả năng phục hồi", example: "Building resilience in children.", note: "Khả năng bật dậy sau khó khăn." },
  { word: "Deteriorate", pos: "Verb", meaning: "Trở nên tồi tệ hơn", example: "The patient's condition began to deteriorate.", note: "Đồng nghĩa: worsen." },
  { word: "Advocacy", pos: "Noun", meaning: "Sự biện hộ/bảo vệ quyền lợi", example: "Child advocacy programs.", note: "Người làm việc này gọi là 'Advocate'." },
  { word: "Sustainable", pos: "Adjective", meaning: "Bền vững", example: "Sustainable development goals.", note: "Động từ: sustain." },
  { word: "Controversy", pos: "Noun", meaning: "Sự tranh cãi", example: "The policy caused a lot of controversy.", note: "Tính từ: controversial." },
  { word: "Precipitate", pos: "Verb", meaning: "Làm thúc đẩy/gây ra (tiêu cực)", example: "The crisis was precipitated by a lack of funds.", note: "Làm chuyện xấu xảy ra nhanh hơn." },
  { word: "Interdependence", pos: "Noun", meaning: "Sự phụ thuộc lẫn nhau", example: "The interdependence of local ecosystems.", note: "Gốc từ: depend." },
  { word: "Cohesive", pos: "Adjective", meaning: "Gắn kết/Dính liền", example: "A cohesive team environment.", note: "Danh từ: cohesion." },
  { word: "Proportionate", pos: "Adjective", meaning: "Cân xứng/Tỷ lệ thuận", example: "The punishment must be proportionate to the crime.", note: "Ngược nghĩa: disproportionate." },
  { word: "Rehabilitation", pos: "Noun", meaning: "Sự phục hồi chức năng/cải tạo", example: "Drug rehabilitation center.", note: "Động từ: rehabilitate." },
  { word: "Predominantly", pos: "Adverb", meaning: "Phần lớn/Chủ yếu", example: "The neighborhood is predominantly residential.", note: "Đồng nghĩa: mainly, mostly." },
  { word: "Accumulate", pos: "Verb", meaning: "Tích lũy", example: "Debts began to accumulate.", note: "Danh từ: accumulation." },
  { word: "Inequality", pos: "Noun", meaning: "Sự bất bình đẳng", example: "Addressing social inequality.", note: "Từ khóa phổ biến trong chính sách xã hội." },
  { word: "Disproportionate", pos: "Adjective", meaning: "Không cân xứng", example: "A disproportionate number of cases.", note: "Gốc từ: proportion." },
  { word: "Unprecedented", pos: "Adjective", meaning: "Chưa từng có tiền lệ", example: "An unprecedented level of success.", note: "Thường dùng trong văn phong báo chí/học thuật." },
  { word: "Bureaucracy", pos: "Noun", meaning: "Quan liêu/Hệ thống hành chính", example: "Hindered by government bureaucracy.", note: "Chữ viết rất khó (b-u-r-e-a-u-c-r-a-c-y)." },
  { word: "Simultaneously", pos: "Adverb", meaning: "Cùng lúc/Đồng thời", example: "The events occurred simultaneously.", note: "Đồng nghĩa: at the same time." },
  { word: "Disseminate", pos: "Verb", meaning: "Gieo rắc/Phổ biến (thông tin)", example: "To disseminate information to the public.", note: "Đồng nghĩa: distribute, spread." },
  { word: "Endeavor", pos: "Noun/Verb", meaning: "Sự cố gắng/Nỗ lực (để đạt được mục đích)", example: "An outstanding endeavor in social care.", note: "Trịnh trọng hơn từ 'attempt'." },
  { word: "Hypothesis", pos: "Noun", meaning: "Giả thuyết", example: "Formulating a scientific hypothesis.", note: "Số nhiều: hypotheses." },
  { word: "Qualitative", pos: "Adjective", meaning: "Định tính", example: "Qualitative research methods.", note: "Thường đi đối lập với định lượng (quantitative)." },
  { word: "Quantitative", pos: "Adjective", meaning: "Định lượng (số liệu)", example: "Gathering quantitative data.", note: "Đi với các phân tích bằng biểu đồ, phần trăm." },
  { word: "Ambiguity", pos: "Noun", meaning: "Sự mơ hồ/Sự tối nghĩa", example: "To avoid any ambiguity, be specific.", note: "Tính từ: ambiguous." },
  { word: "Exacerbate", pos: "Verb", meaning: "Làm trầm trọng thêm", example: "This policy will only exacerbate the problem.", note: "Từ học thuật hay gặp thay thế cho 'make worse'." },
  { word: "Mitigate", pos: "Verb", meaning: "Làm dịu bớt/Làm khỏa lấp", example: "Strategies to mitigate the impact of poverty.", note: "Đồng nghĩa: alleviate, reduce." },
  { word: "Paradigm", pos: "Noun", meaning: "Mô hình/Hệ điều kiện", example: "A paradigm shift in education.", note: "Đọc là /ˈpæ.rə.daɪm/." },
  { word: "Subordinate", pos: "Noun/Adjective", meaning: "Cấp dưới/Lệ thuộc", example: "A subordinate role in the project.", note: "Trong ngữ pháp: subordinate clause (mệnh đề phụ)." },
  { word: "Intrinsic", pos: "Adjective", meaning: "Bản chất/Bên trong", example: "The intrinsic value of education.", note: "Đối lập với 'Extrinsic' (ngoại sinh)." },
  { word: "Pernicious", pos: "Adjective", meaning: "Độc hại/Nguy hiểm", example: "The pernicious effects of social media.", note: "Thường dùng để chỉ sự phá hoại ngầm, từ từ." },
  { word: "Obsolete", pos: "Adjective", meaning: "Lỗi thời/Cũ rích", example: "Many textbooks are becoming obsolete.", note: "Đồng nghĩa: outdated." },
  { word: "Detrimental", pos: "Adjective", meaning: "Có hại/Bất lợi", example: "Smoking is detrimental to health.", note: "Luôn đi kèm với giới từ 'to'. Đồng nghĩa: harmful." },
  { word: "Ameliorate", pos: "Verb", meaning: "Cải thiện/Làm tốt hơn", example: "Efforts to ameliorate living standards.", note: "Từ học thuật của 'improve'." },
  { word: "Respective", pos: "Adjective", meaning: "Tương ứng/Riêng của mỗi người", example: "They returned to their respective homes.", note: "Đừng nhầm với Respectful (lễ phép) hay Respectable (đáng kính)." },
  { word: "Tangible", pos: "Adjective", meaning: "Hữu hình/Có thể sờ thấy", example: "Tangible benefits of the program.", note: "Đối lập với 'Intangible' (Vô hình)." },
  { word: "Ubiquitous", pos: "Adjective", meaning: "Có mặt ở khắp nơi", example: "Smartphones have become ubiquitous.", note: "Đồng nghĩa: everywhere, prevalent." },
  { word: "Proponent", pos: "Noun", meaning: "Người ủng hộ", example: "He is a strong proponent of educational reform.", note: "Đối lập: Opponent (Người phản đối)." },
  { word: "Acquisition", pos: "Noun", meaning: "Sự đạt được/sự thu nạp", example: "Language acquisition in infants.", note: "Thường dùng trong cụm 'knowledge/language acquisition'." },
  { word: "Discourse", pos: "Noun", meaning: "Bài luận/Sự đàm thoại", example: "Academic discourse on society.", note: "Hay gặp trong chuyên ngành Ngôn ngữ học/Xã hội học." },
  { word: "Empathy", pos: "Noun", meaning: "Sự thấu cảm", example: "Social workers must show empathy.", note: "Khác với 'Sympathy' (Sự thông cảm/thương xót)." },
  { word: "Correlation", pos: "Noun", meaning: "Sự tương quan", example: "A strong correlation between poverty and crime.", note: "Nghiên cứu số liệu cực kỳ hay dùng từ này." },
  { word: "Implication", pos: "Noun", meaning: "Hàm ý/Hệ quả tiềm ẩn", example: "The social implications of the new policy.", note: "Verb: imply." },
  { word: "Cognitive", pos: "Adjective", meaning: "Thuộc về nhận thức", example: "Cognitive development in children.", note: "Ngành TLH/GDH sử dụng liên tục." },
  { word: "Pragmatic", pos: "Adjective", meaning: "Thực dụng/Thực tế", example: "A pragmatic approach to solving problems.", note: "Từ chuyên ngành nói về sự giải quyết bằng thực tiễn thay vì lý thuyết." },
  { word: "Autonomy", pos: "Noun", meaning: "Sự tự trị/Quyền tự quyết", example: "Encouraging learner autonomy.", note: "Từ rất ăn điểm trong writing và đọc." },
  { word: "Efficacy", pos: "Noun", meaning: "Tính hiệu quả (của phương pháp/vật lí)", example: "The efficacy of the treatment.", note: "Cẩn thận nhầm với efficiency." },
  { word: "Manifestation", pos: "Noun", meaning: "Sự biểu hiện/Dấu hiệu", example: "A physical manifestation of stress.", note: "Động từ: manifest." },
  { word: "Trajectory", pos: "Noun", meaning: "Quỹ đạo/Hướng phát triển", example: "The upward trajectory of their career.", note: "Có thể dùng theo nghĩa bóng cho đường lối/nghề nghiệp." },
  { word: "Paradox", pos: "Noun", meaning: "Sự nghịch lý", example: "It is a paradox that the richest country has so much poverty.", note: "Điều có vẻ vô lý nhưng lại là sự thật." },
  { word: "Conundrum", pos: "Noun", meaning: "Câu đố/vấn đề nan giải", example: "A difficult conundrum facing the government.", note: "Từ đồng nghĩa mang hình thái cao cấp cho chữ 'problem'." },
  { word: "Disparity", pos: "Noun", meaning: "Sự chênh lệch/khác biệt (về thu nhập, vị thế)", example: "Economic disparity between regions.", note: "Nặng đô hơn 'difference' một chút trong văn thuật." },
  { word: "Plausible", pos: "Adjective", meaning: "Hợp lý/Đáng tin", example: "A plausible excuse.", note: "Có khả năng là đúng/xảy ra được." },
  { word: "Tentative", pos: "Adjective", meaning: "Dự kiến/Không chắc chắn", example: "We made tentative plans for the weekend.", note: "Chưa chốt, còn có thể thay đổi." },
  { word: "Subtle", pos: "Adjective", meaning: "Tinh tế/Tế nhị (khó nhận ra)", example: "A subtle difference.", note: "Chữ 'b' là âm câm, đọc là /ˈsʌt.əl/." },
  { word: "Coherent", pos: "Adjective", meaning: "Mạch lạc/Chặt chẽ", example: "A coherent argument.", note: "Trong thi viết/nói hay có tiêu chí Coherence." },
  { word: "Eclectic", pos: "Adjective", meaning: "Mang tính chắt lọc/Pha trộn đa dạng", example: "His taste in music is eclectic.", note: "Từ ghép lại từ nhiều nguồn khác nhau." },
  { word: "Scrutiny", pos: "Noun", meaning: "Sự kiểm tra kỹ lưỡng", example: "The project came under close scrutiny.", note: "Gắn liền với việc điều tra/đánh giá khắt khe." },
  { word: "Inherent", pos: "Adjective", meaning: "Vốn có/Cố hữu", example: "The risks inherent in the procedure.", note: "Những thuộc tính không thể tách rời." },
  { word: "Notorious", pos: "Adjective", meaning: "Khét tiếng/Tai tiếng", example: "He is notorious for his bad temper.", note: "Trái ngược lại sự danh tiếng (famous nhưng mang nghĩa xấu)." },
  { word: "Diligent", pos: "Adjective", meaning: "Siêng năng/Cần mẫn", example: "A diligent student.", note: "Cao cấp và hay hơn 'hardworking'." },
  { word: "Versatile", pos: "Adjective", meaning: "Đa năng/Linh hoạt", example: "A highly versatile tool.", note: "Người có thể làm nhiều vị trí cũng gọi là versatile." },
  { word: "Imminent", pos: "Adjective", meaning: "Sắp xảy ra (đến nơi)", example: "In imminent danger.", note: "Thường đi kèm với những hiểm họa lập tức." },
  { word: "Incentive", pos: "Noun", meaning: "Sự khích lệ/Sự động viên", example: "Financial incentives to work harder.", note: "Cung cấp động lực để thực hiện gì đó." },
  { word: "Compensate", pos: "Verb", meaning: "Bồi thường/Bù đắp", example: "To compensate for the loss of time.", note: "Đi với giới từ FOR." },
  { word: "Constraint", pos: "Noun", meaning: "Sự hạn chế/Sự ép buộc", example: "Time constraints make it difficult.", note: "Cụm hay gặp: 'under constraint'." },
  { word: "Inhibit", pos: "Verb", meaning: "Ngăn chặn/Hạn chế", example: "Fear can inhibit your progress.", note: "Đồng nghĩa: prevent, restrict." },
  { word: "Viable", pos: "Adjective", meaning: "Khả thi", example: "A viable solution.", note: "Có khả năng thực thi và hoạt động tốt." },
  { word: "Adequate", pos: "Adjective", meaning: "Đầy đủ/Tương xứng", example: "Provide adequate training.", note: "Đồng nghĩa của chữ sufficient / enough." },
  { word: "Deficient", pos: "Adjective", meaning: "Thiếu hụt/Kém cỏi", example: "A diet deficient in vitamin C.", note: "Danh từ: deficiency." },
  { word: "Mandatory", pos: "Adjective", meaning: "Bắt buộc", example: "Attendance is mandatory.", note: "Ngược lại: Optional (Tùy chọn)." },
  { word: "Obligation", pos: "Noun", meaning: "Nghĩa vụ/Bổn phận", example: "You have a legal obligation.", note: "Nhiệm vụ phải làm, động từ: oblige." },
  { word: "Aspiration", pos: "Noun", meaning: "Khát vọng/Niềm hy vọng", example: "Career aspirations.", note: "Như một khao khát cháy bỏng đạt được mục tiêu." },
  { word: "Apathy", pos: "Noun", meaning: "Sự thờ ơ/Vô cảm", example: "Public apathy towards politics.", note: "Tính từ: apathetic (thiếu sự quan tâm)." },
  { word: "Consensus", pos: "Noun", meaning: "Sự đồng thuận", example: "To reach a consensus.", note: "Không dùng cụm 'general consensus' vì bị dư thừa chữ 'general'." },
  { word: "Vindicate", pos: "Verb", meaning: "Minh oan/Chứng minh là đúng", example: "He was vindicated by the evidence.", note: "Đưa ra bằng chứng gỡ các cáo buộc." },
  { word: "Pivotal", pos: "Adjective", meaning: "Chủ chốt/Nòng cốt", example: "A pivotal role in the project.", note: "Giống như trung tâm hay nền tảng (a key role)." },
  { word: "Encompass", pos: "Verb", meaning: "Bao gồm/Chứa đựng", example: "The course will encompass various topics.", note: "Rất hay cho Writing khi miêu tả tính bao quát." },
  { word: "Foster", pos: "Verb", meaning: "Bồi dưỡng/Cổ vũ sự phát triển", example: "To foster a sense of community.", note: "Ngoài ra: foster parents (bố mẹ nuôi)." },
  { word: "Jeopardize", pos: "Verb", meaning: "Gây nguy hiểm/Liều lĩnh", example: "Do not jeopardize your career.", note: "Một từ rất ấn tượng trong bài làm: Đặt cái gì đó vào rủi ro lớn." },
  { word: "Lucrative", pos: "Adjective", meaning: "Sinh lợi cao/Màu mỡ (ngành nghề)", example: "A highly lucrative business.", note: "Sử dụng cho kinh doanh và các nguồn tiền/nghề hot." }
];
