export const VOCABULARY_LIST = [
  { word: 'social', pos: 'adj', meaning: 'thuộc về xã hội, liên quan đến xã hội', example: 'Social workers help individuals in need.', note: 'Từ khóa cốt lõi của ngành công tác xã hội.' },
  { word: 'profession', pos: 'n', meaning: 'nghề nghiệp, chuyên môn', example: 'Social work is a demanding profession.', note: 'Thường chỉ các công việc đòi hỏi chuyên môn cao.' },
  { word: 'specialized', pos: 'adj', meaning: 'chuyên biệt, chuyên môn hóa', example: 'It is a specialized area of practice.', note: 'Bắt nguồn từ động từ "specialize".' },
  { word: 'practice', pos: 'n', meaning: 'hoạt động thực tiễn, ngành nghề', example: 'She has a successful social work practice.', note: 'Ngoài nghĩa "thực hành", còn nghĩa là cơ sở làm việc/thực tiễn nghề.' },
  { word: 'broad', pos: 'adj', meaning: 'rộng, bao quát', example: 'Within the broad field of social work.', note: 'Trái nghĩa: narrow (hẹp).' },
  { word: 'unique', pos: 'adj', meaning: 'độc đáo, duy nhất', example: 'They bring unique knowledge to the school.', note: 'Nhấn mạnh sự khác biệt và đặc biệt.' },
  { word: 'knowledge', pos: 'n', meaning: 'kiến thức, sự hiểu biết', example: 'Knowledge of human behavior is essential.', note: 'Danh từ không đếm được.' },
  { word: 'skills', pos: 'n', meaning: 'kỹ năng', example: 'Social workers bring analytical skills.', note: 'Thường dùng ở số nhiều.' },
  { word: 'system', pos: 'n', meaning: 'hệ thống', example: 'They work within the school system.', note: 'Có thể chỉ hệ thống trường học hoặc xã hội.' },
  { word: 'mental', pos: 'adj', meaning: 'thuộc về tinh thần, tâm thần', example: 'Mental health is a top priority.', note: 'Hay đi kèm với health (sức khỏe tâm thần).' },
  { word: 'health', pos: 'n', meaning: 'sức khỏe', example: 'They assist with mental health concerns.', note: 'Bao gồm cả thể chất (physical) và tinh thần (mental).' },
  { word: 'professional', pos: 'n', meaning: 'chuyên gia, người có chuyên môn', example: 'They are trained mental health professionals.', note: 'Vừa là danh từ vừa là tính từ.' },
  { word: 'assist', pos: 'v', meaning: 'hỗ trợ, giúp đỡ', example: 'Professionals who can assist with concerns.', note: 'Đồng nghĩa: help, support.' },
  { word: 'concern', pos: 'n', meaning: 'vấn đề, mối bận tâm', example: 'Students facing behavioral concerns.', note: 'Đồng nghĩa: issue, problem.' },
  { word: 'behavioral', pos: 'adj', meaning: 'thuộc về hành vi', example: 'Implementing positive behavioral support.', note: 'Bắt nguồn từ danh từ "behavior" (hành vi).' },
  { word: 'positive', pos: 'adj', meaning: 'tích cực', example: 'Positive support is crucial for students.', note: 'Trái nghĩa: negative (tiêu cực).' },
  { word: 'support', pos: 'n, v', meaning: 'sự hỗ trợ, hỗ trợ', example: 'They provide academic and classroom support.', note: 'Hay dùng trong cả ngữ cảnh vật chất lẫn tinh thần.' },
  { word: 'academic', pos: 'adj', meaning: 'thuộc về học thuật, trường lớp', example: 'To meet its academic mission.', note: 'Liên quan đến giáo dục, học tập.' },
  { word: 'classroom', pos: 'n', meaning: 'phòng học, lớp học', example: 'Classroom support helps teachers directly.', note: 'Môi trường học tập chính thức.' },
  { word: 'consultation', pos: 'n', meaning: 'sự tham vấn, hội ý', example: 'Consultation with teachers and parents.', note: 'Danh từ của động từ "consult".' },
  { word: 'administrator', pos: 'n', meaning: 'quản lý, nhà quản trị', example: 'Working alongside school administrators.', note: 'Chỉ ban giám hiệu hoặc người điều hành.' },
  { word: 'provide', pos: 'v', meaning: 'cung cấp', example: 'They provide individual counseling.', note: 'Cấu trúc: provide sb with sth.' },
  { word: 'individual', pos: 'adj, n', meaning: 'cá nhân', example: 'Providing individual and group therapy.', note: 'Trái nghĩa: group, collective.' },
  { word: 'group', pos: 'n', meaning: 'nhóm', example: 'Group therapy is highly effective.', note: 'Nhấn mạnh sự tương tác cộng đồng.' },
  { word: 'counseling', pos: 'n', meaning: 'tư vấn, tham vấn tâm lý', example: 'Students may need academic counseling.', note: 'Được thực hiện bởi counselor (chuyên gia tư vấn).' },
  { word: 'therapy', pos: 'n', meaning: 'trị liệu', example: 'Therapy helps with emotional issues.', note: 'Phương pháp điều trị tâm lý hoặc thể chất.' },
  { word: 'instrumental', pos: 'adj', meaning: 'đóng vai trò quan trọng/cốt yếu', example: 'They are instrumental in furthering the mission.', note: 'Nghĩa bóng: là công cụ đóng góp chính.' },
  { word: 'further', pos: 'v', meaning: 'thúc đẩy, tiến xa hơn', example: 'Instrumental in furthering the mission.', note: 'Có thể dùng như động từ mang nghĩa phát triển.' },
  { word: 'mission', pos: 'n', meaning: 'sứ mệnh, nhiệm vụ', example: 'Enhancing the district academic mission.', note: 'Mục tiêu lớn và lâu dài.' },
  { word: 'setting', pos: 'n', meaning: 'môi trường, bối cảnh', example: 'Providing a setting for teaching.', note: 'Đồng nghĩa: environment, context.' },
  { word: 'teaching', pos: 'n', meaning: 'việc giảng dạy', example: 'A setting for teaching and learning.', note: 'Hoạt động truyền đạt kiến thức.' },
  { word: 'learning', pos: 'n', meaning: 'việc học tập', example: 'Learning is a lifelong process.', note: 'Quá trình tiếp thu kiến thức.' },
  { word: 'attainment', pos: 'n', meaning: 'sự đạt được, thành tựu', example: 'For the attainment of competence.', note: 'Danh từ của động từ "attain".' },
  { word: 'competence', pos: 'n', meaning: 'năng lực, sự thạo việc', example: 'Attainment of competence and confidence.', note: 'Khả năng thực hiện tốt một việc gì đó.' },
  { word: 'confidence', pos: 'n', meaning: 'sự tự tin', example: 'Building students confidence is key.', note: 'Lòng tin vào khả năng của bản thân.' },
  { word: 'hire', pos: 'v', meaning: 'thuê, tuyển dụng', example: 'Are hired by school districts.', note: 'Đồng nghĩa: employ, recruit.' },
  { word: 'district', pos: 'n', meaning: 'học khu, khu vực', example: 'Hired by school districts.', note: 'Cơ quan quản lý giáo dục địa phương (ở Mỹ).' },
  { word: 'enhance', pos: 'v', meaning: 'tăng cường, nâng cao', example: 'To enhance the ability to meet goals.', note: 'Làm cho điều gì đó trở nên tốt hơn.' },
  { word: 'ability', pos: 'n', meaning: 'khả năng', example: 'The ability to meet academic missions.', note: 'Năng lực làm được việc gì.' },
  { word: 'especially', pos: 'adv', meaning: 'đặc biệt là', example: 'Especially where collaboration is key.', note: 'Nhấn mạnh một điểm cụ thể.' },
  { word: 'collaboration', pos: 'n', meaning: 'sự hợp tác', example: 'Community collaboration achieves success.', note: 'Hợp tác giữa nhiều bên.' },
  { word: 'achieve', pos: 'v', meaning: 'đạt được', example: 'Achieving student success.', note: 'Thành công sau nỗ lực.' },
  { word: 'success', pos: 'n', meaning: 'sự thành công', example: 'The ultimate goal is student success.', note: 'Kết quả tốt đẹp.' },
  { word: 'degree', pos: 'n', meaning: 'bằng cấp', example: 'Professionals with a degree in social work.', note: 'Chứng chỉ tốt nghiệp đại học/sau đại học.' },
  { word: 'related', pos: 'adj', meaning: 'có liên quan', example: 'Services related to social adjustment.', note: 'Thường đi với giới từ "to".' },
  { word: 'emotional', pos: 'adj', meaning: 'thuộc về cảm xúc', example: 'Social, emotional and life adjustment.', note: 'Liên quan đến tâm lý, tình cảm.' },
  { word: 'adjustment', pos: 'n', meaning: 'sự điều chỉnh, sự thích ứng', example: 'Adjustment to school or society.', note: 'Thường thấy đối với học sinh mới hòa nhập.' },
  { word: 'society', pos: 'n', meaning: 'xã hội', example: 'Integrating students into society.', note: 'Tập thể cộng đồng con người.' },
  { word: 'link', pos: 'n', meaning: 'sự kết nối, mắt xích', example: 'They are the link between home and school.', note: 'Cầu nối giữa các bên.' },
  { word: 'direct', pos: 'adj', meaning: 'trực tiếp', example: 'Providing direct as well as indirect services.', note: 'Không qua trung gian.' },
  { word: 'indirect', pos: 'adj', meaning: 'gián tiếp', example: 'Providing indirect services like policy making.', note: 'Thông qua các yếu tố phụ trợ.' },
  { word: 'personnel', pos: 'n', meaning: 'nhân sự, đội ngũ nhân viên', example: 'Services to school personnel.', note: 'Chỉ toàn bộ người lao động trong cơ quan.' },
  { word: 'promote', pos: 'v', meaning: 'thúc đẩy, thăng tiến', example: 'To promote student success.', note: 'Khuyến khích sự phát triển.' },
  { word: 'victims', pos: 'n', meaning: 'nạn nhân', example: 'Victims of many social forces.', note: 'Người chịu tổn thương do tác động bên ngoài.' },
  { word: 'force', pos: 'n', meaning: 'thế lực, lực lượng', example: 'Social forces that negatively affect students.', note: 'Yếu tố vô hình tạo áp lực.' },
  { word: 'negatively', pos: 'adv', meaning: 'một cách tiêu cực', example: 'Factors that negatively affect learning.', note: 'Gây ảnh hưởng xấu.' },
  { word: 'affect', pos: 'v', meaning: 'ảnh hưởng đến', example: 'Forces that affect their role.', note: 'Tác động làm thay đổi.' },
  { word: 'role', pos: 'n', meaning: 'vai trò', example: 'Their role as students.', note: 'Vị trí và chức năng trong xã hội.' },
  { word: 'state', pos: 'n', meaning: 'tình trạng, trạng thái', example: 'The family is in a state of change.', note: 'Giai đoạn hoặc điều kiện hiện tại.' },
  { word: 'stabilize', pos: 'v', meaning: 'ổn định lại', example: 'Until the family becomes stabilized.', note: 'Làm cho bớt biến động.' },
  { word: 'unmet', pos: 'adj', meaning: 'chưa được đáp ứng', example: 'Children unmet physical needs.', note: 'Hay dùng kết hợp: unmet needs (nhu cầu chưa được thỏa mãn).' },
  { word: 'physical', pos: 'adj', meaning: 'thuộc về thể chất', example: 'Unmet physical and emotional needs.', note: 'Trái nghĩa với mental (tinh thần).' },
  { word: 'interfere', pos: 'v', meaning: 'cản trở, can thiệp', example: 'Will interfere with their ability to learn.', note: 'Làm gián đoạn quá trình.' },
  { word: 'adjust', pos: 'v', meaning: 'điều chỉnh, thích nghi', example: 'Ability to learn and adjust in school.', note: 'Làm quen với môi trường mới.' },
  { word: 'identify', pos: 'v', meaning: 'nhận diện, phát hiện', example: 'Identifies students having problems.', note: 'Tìm ra và xác định vấn đề.' },
  { word: 'failing', pos: 'adj', meaning: 'thất bại, sa sút', example: 'Academic problems like failing grades.', note: 'Điểm số kém, không đạt yêu cầu.' },
  { word: 'grade', pos: 'n', meaning: 'điểm số, cấp học', example: 'Failing grades are a warning sign.', note: 'Thành tích học tập được đánh giá.' },
  { word: 'attendance', pos: 'n', meaning: 'sự chuyên cần, việc đi học', example: 'Attendance problems affect studying.', note: 'Vấn đề vắng mặt ảnh hưởng đến kết quả.' },
  { word: 'incomplete', pos: 'adj', meaning: 'bỏ dở, chưa hoàn thành', example: 'Resulting in incomplete work.', note: 'Bài tập hoặc nhiệm vụ chưa làm xong.' },
  { word: 'bullying', pos: 'n', meaning: 'bắt nạt', example: 'Being a victim of bullying.', note: 'Vấn đề bạo lực học đường phổ biến.' },
  { word: 'peer', pos: 'n', meaning: 'bạn đồng trang lứa', example: 'Peer pressure is tough for teenagers.', note: 'Chỉ những người cùng độ tuổi hoặc địa vị.' },
  { word: 'pressure', pos: 'n', meaning: 'áp lực', example: 'Negative peer pressure causes stress.', note: 'Căng thẳng do kỳ vọng bên ngoài.' },
  { word: 'dismiss', pos: 'v', meaning: 'bỏ qua, xem nhẹ', example: 'Dismissing school policies.', note: 'Không tuân thủ các nguyên tắc.' },
  { word: 'policy', pos: 'n', meaning: 'chính sách, quy định', example: 'Respecting school policies.', note: 'Nguyên tắc do nhà trường đặt ra.' },
  { word: 'substance', pos: 'n', meaning: 'chất gây nghiện, vật chất', example: 'Substance abuse is a major problem.', note: 'Trong y tế thường chỉ rươu, ma túy.' },
  { word: 'abuse', pos: 'n', meaning: 'sự lạm dụng, bạo hành', example: 'Substance abuse or family abuse.', note: 'Việc sử dụng sai mục đích hoặc gây hại.' },
  { word: 'neglect', pos: 'n, v', meaning: 'sự bỏ bê, xao nhãng', example: 'Child neglect at home.', note: 'Thiếu sự chăm sóc cần thiết.' },
  { word: 'poverty', pos: 'n', meaning: 'đói nghèo', example: 'Poverty significantly affects education.', note: 'Hoàn cảnh thiếu thốn vật chất.' },
  { word: 'determine', pos: 'v', meaning: 'xác định, tìm ra', example: 'To determine the cause through testing.', note: 'Phân tích để tìm lý do cốt lõi.' },
  { word: 'cause', pos: 'n', meaning: 'nguyên nhân', example: 'Determine the cause of the problem.', note: 'Lý do bắt nguồn vấn đề.' },
  { word: 'observe', pos: 'v', meaning: 'quan sát', example: 'Through observing the student.', note: 'Theo dõi hành vi để đánh giá.' },
  { word: 'interview', pos: 'v', meaning: 'phỏng vấn, trò chuyện', example: 'Interviewing families for context.', note: 'Trao đổi lấy thông tin trực tiếp.' },
  { word: 'testing', pos: 'n', meaning: 'kiểm tra, trắc nghiệm', example: 'Psychological testing processes.', note: 'Đánh giá năng lực hoặc tâm lý.' },
  { word: 'create', pos: 'v', meaning: 'tạo ra, xây dựng', example: 'Creates plans for students.', note: 'Thiết lập các kế hoạch.' },
  { word: 'arrange', pos: 'v', meaning: 'sắp xếp', example: 'Arranging special classes.', note: 'Lên lịch hoặc chuẩn bị tổ chức.' },
  { word: 'special', pos: 'adj', meaning: 'đặc biệt', example: 'Special education assessment.', note: 'Dành riêng cho đối tượng cụ thể.' },
  { word: 'disability', pos: 'n', meaning: 'khuyết tật, khiếm khuyết', example: 'Students with learning disabilities.', note: 'Bao gồm khuyết tật học tập và thể chất.' },
  { word: 'prevention', pos: 'n', meaning: 'sự phòng ngừa', example: 'Bullying prevention programs.', note: 'Ngăn chặn vấn đề trước khi xảy ra.' },
  { word: 'stress', pos: 'n', meaning: 'căng thẳng', example: 'Counseling students with stress.', note: 'Áp lực tâm lý.' },
  { word: 'anxiety', pos: 'n', meaning: 'lo âu', example: 'Dealing with stress and anxiety.', note: 'Trạng thái bồn chồn lo lắng.' },
  { word: 'depression', pos: 'n', meaning: 'trầm cảm', example: 'Depression is a mental illness.', note: 'Bệnh lý liên quan đến rối loạn tâm trạng.' },
  { word: 'assessment', pos: 'n', meaning: 'sự đánh giá', example: 'Special education assessment.', note: 'Kiểm tra đo lường năng lực.' },
  { word: 'meeting', pos: 'n', meaning: 'cuộc họp', example: 'Educational Planning Meetings.', note: 'Hội ý định kỳ.' },
  { word: 'mobilize', pos: 'v', meaning: 'huy động', example: 'Mobilizing resources for the child.', note: 'Tập hợp các nguồn lực để hỗ trợ.' },
  { word: 'resource', pos: 'n', meaning: 'nguồn lực, tài nguyên', example: 'Community and family resources.', note: 'Thường bao gồm tài chính, con người.' },
  { word: 'crisis', pos: 'n', meaning: 'khủng hoảng', example: 'Providing crisis intervention.', note: 'Sự cố khẩn cấp cần giải quyết ngay.' },
  { word: 'intervention', pos: 'n', meaning: 'sự can thiệp', example: 'Crisis intervention strategies.', note: 'Tác động để thay đổi tình hình.' },
  { word: 'strategy', pos: 'n', meaning: 'chiến lược', example: 'Developing intervention strategies.', note: 'Kế hoạch lâu dài.' },
  { word: 'conflict', pos: 'n', meaning: 'xung đột', example: 'Conflict resolution skills.', note: 'Sự mâu thuẫn giữa các bên.' },
  { word: 'resolution', pos: 'n', meaning: 'sự giải quyết', example: 'Conflict resolution is important.', note: 'Cách tháo gỡ vấn đề.' },
  { word: 'anger', pos: 'n', meaning: 'sự tức giận', example: 'Anger management programs.', note: 'Cảm xúc tiêu cực cần kiểm soát.' },
  { word: 'management', pos: 'n', meaning: 'sự quản lý, kiểm soát', example: 'Behavior management techniques.', note: 'Điều hành và xử lý.' },
  { word: 'interaction', pos: 'n', meaning: 'sự tương tác', example: 'Social interaction skills.', note: 'Giao tiếp qua lại.' },
  { word: 'facilitate', pos: 'v', meaning: 'tạo điều kiện, hỗ trợ', example: 'Facilitating school adjustment.', note: 'Làm cho việc gì đó dễ dàng hơn.' },
  { word: 'alleviate', pos: 'v', meaning: 'làm giảm bớt, xoa dịu', example: 'Alleviating family stress.', note: 'Làm nhẹ đi các triệu chứng/vấn đề.' },
  { word: 'access', pos: 'v, n', meaning: 'tiếp cận', example: 'Accessing specialized programs.', note: 'Tìm kiếm đường dẫn tới dịch vụ.' },
  { word: 'utilize', pos: 'v', meaning: 'sử dụng, tận dụng', example: 'Utilizing community resources.', note: 'Dùng cái gì đó hiệu quả.' },
  { word: 'information', pos: 'n', meaning: 'thông tin', example: 'Providing information about factors.', note: 'Danh từ không đếm được.' },
  { word: 'essential', pos: 'adj', meaning: 'thiết yếu, cực kỳ quan trọng', example: 'Essential information for teachers.', note: 'Không thể thiếu.' },
  { word: 'factor', pos: 'n', meaning: 'yếu tố', example: 'Cultural and societal factors.', note: 'Thành phần ảnh hưởng chung.' },
  { word: 'cultural', pos: 'adj', meaning: 'thuộc về văn hóa', example: 'Cultural factors affecting learning.', note: 'Liên quan đến phong tục, tập quán.' },
  { word: 'societal', pos: 'adj', meaning: 'thuộc về xã hội (vĩ mô)', example: 'Societal and economic issues.', note: 'Quy mô xã hội rộng lớn.' },
  { word: 'economic', pos: 'adj', meaning: 'thuộc về tài chính, kinh tế', example: 'Economic barriers to schooling.', note: 'Liên quan đến tiền bạc.' },
  { word: 'familial', pos: 'adj', meaning: 'thuộc về gia đình', example: 'Familial health and behavior.', note: 'Từ đồng gốc với "family".' },
  { word: 'performance', pos: 'n', meaning: 'hiệu suất, kết quả thực hiện', example: 'Affecting a students performance.', note: 'Thành tích gặt hái được.' },
  { word: 'behavior', pos: 'n', meaning: 'hành vi', example: 'Assisting teachers with behavior management.', note: 'Cách cư xử.' },
  { word: 'training', pos: 'n', meaning: 'đào tạo, huấn luyện', example: 'Developing training programs.', note: 'Nâng cao trình độ.' },
  { word: 'liaison', pos: 'n', meaning: 'liên lạc viên, sự phối hợp', example: 'School-Community Liaison duties.', note: 'Cầu nối, liên kết tổ chức.' },
  { word: 'coordinate', pos: 'v', meaning: 'phối hợp, điều phối', example: 'Coordinating community resources.', note: 'Gắn kết các thành phần lại nhau.' },
  { word: 'obtain', pos: 'v', meaning: 'đạt được, thu được', example: 'Obtaining support from agencies.', note: 'Đồng nghĩa: get, acquire.' },
  { word: 'agency', pos: 'n', meaning: 'cơ quan, tổ chức', example: 'Mental health agencies.', note: 'Đơn vị thực hiện dịch vụ.' },
  { word: 'advocate', pos: 'v, n', meaning: 'biện hộ, ủng hộ, người bảo vệ', example: 'Advocating for new services.', note: 'Luôn bảo vệ quyền lợi của thân chủ.' },
  { word: 'improve', pos: 'v', meaning: 'cải thiện', example: 'Improved community service.', note: 'Làm tốt hơn trước.' },
  { word: 'system', pos: 'n', meaning: 'hệ thống', example: 'Helping the system respond effectively.', note: 'Mạng lưới hoạt động chung.' },
  { word: 'respond', pos: 'v', meaning: 'phản hồi, đáp ứng', example: 'Respond effectively to each child.', note: 'Phản ứng lại tác động.' },
  { word: 'effectively', pos: 'adv', meaning: 'một cách hiệu quả', example: 'Working effectively in school.', note: 'Mang lại lợi ích tốt nhất.' },
  { word: 'implement', pos: 'v', meaning: 'triển khai, thực thi', example: 'Implementing educational programs.', note: 'Đồng nghĩa: execute, apply.' },
  { word: 'exceptional', pos: 'adj', meaning: 'ngoại lệ, xuất chúng, đặc biệt', example: 'Programs for exceptional children.', note: 'Trẻ có nhu cầu đặc biệt.' },
  { word: 'alternative', pos: 'adj, n', meaning: 'thay thế, mang tính lựa chọn', example: 'Alternative programs for drop-outs.', note: 'Dành cho đối tượng không theo mô hình chuẩn.' },
  { word: 'dropout', pos: 'n', meaning: 'người bỏ học', example: 'Programs for school drop-outs.', note: 'Trẻ rời khỏi trường học sớm.' },
  { word: 'truant', pos: 'n', meaning: 'học sinh trốn học', example: 'Programs for truants and delinquents.', note: 'Người trốn học vì vô kỷ luật.' },
  { word: 'delinquent', pos: 'n', meaning: 'trẻ em phạm tội', example: 'Rehabilitation for juvenile delinquents.', note: 'Những người vị thành niên lệch chuẩn pháp lý.' },
  { word: 'report', pos: 'v', meaning: 'báo cáo', example: 'Reporting child abuse.', note: 'Trình báo cho chính quyền.' },
  { word: 'law', pos: 'n', meaning: 'luật pháp', example: 'Consultation regarding school law.', note: 'Quy định pháp lý bắt buộc.' },
  { word: 'case', pos: 'n', meaning: 'ca bệnh, trường hợp', example: 'Providing case management.', note: 'Quản lý trên từng cá thể riêng biệt.' },
  { word: 'multiple', pos: 'adj', meaning: 'nhiều, phức tạp', example: 'Families requiring multiple resources.', note: 'Một số lượng có hạng mục.' },
  { word: 'scope', pos: 'n', meaning: 'phạm vi', example: 'The scope of social work practice.', note: 'Khoảng hoặc ranh giới hành nghề.' },
  { word: 'overview', pos: 'n', meaning: 'tổng quan', example: 'An overview of the role.', note: 'Cái nhìn khái quát.' },
  { word: 'contribution', pos: 'n', meaning: 'sự đóng góp', example: 'The contribution of social work.', note: 'Thành quả tạo ra cộng đồng.' },
  { word: 'field', pos: 'n', meaning: 'lĩnh vực', example: 'Working in the disability field.', note: 'Khu vực chuyên ngành.' },
  { word: 'concise', pos: 'adj', meaning: 'ngắn gọn, súc tích', example: 'In a concise and informative manner.', note: 'Rõ ràng, không thừa thãi.' },
  { word: 'accessible', pos: 'adj', meaning: 'có thể tiếp cận, dễ hiểu', example: 'Making information accessible.', note: 'Không bị cản trở.' },
  { word: 'informative', pos: 'adj', meaning: 'cung cấp nhiều thông tin', example: 'An informative manner.', note: 'Có ích cho người đọc.' },
  { word: 'manner', pos: 'n', meaning: 'cách thức', example: 'In an accessible manner.', note: 'Cách trình bày.' },
  { word: 'crucial', pos: 'adj', meaning: 'thiết yếu, mang tính quyết định', example: 'The crucial role of social workers.', note: 'Đồng nghĩa: essential, critical.' },
  { word: 'employer', pos: 'n', meaning: 'nhà tuyển dụng, phía người dùng lao động', example: 'Services that employers expect.', note: 'Cơ quan cấp trên.' },
  { word: 'client', pos: 'n', meaning: 'khách hàng, thân chủ', example: 'Services clients can expect.', note: 'Người thụ hưởng dịch vụ.' },
  { word: 'expect', pos: 'v', meaning: 'kỳ vọng, mong chờ', example: 'What clients can expect.', note: 'Chờ đợi kết quả.' },
  { word: 'discuss', pos: 'v', meaning: 'thảo luận', example: 'These are discussed within a range...', note: 'Bàn bạc chi tiết.' },
  { word: 'range', pos: 'n', meaning: 'phạm vi, quy mô', example: 'A range of practice contexts.', note: 'Tập hợp sự lựa chọn.' },
  { word: 'context', pos: 'n', meaning: 'ngữ cảnh, tình hình bối cảnh', example: 'In different practice contexts.', note: 'Hoàn cảnh xung quanh.' },
  { word: 'scheme', pos: 'n', meaning: 'cơ chế, kế hoạch tổ chức', example: 'National Disability Insurance Scheme.', note: 'Thường là từ chính phủ ban hành.' },
  { word: 'comprehensively', pos: 'adv', meaning: 'một cách toàn diện', example: 'Comprehensively changing the field.', note: 'Tác động khắp mọi mặt.' },
  { word: 'change', pos: 'v, n', meaning: 'thay đổi', example: 'Changing the disability field.', note: 'Biến đổi trạng thái.' },
  { word: 'condition', pos: 'n', meaning: 'điều kiện', example: 'Bringing new conditions.', note: 'Tiêu chuẩn thực thi.' },
  { word: 'structure', pos: 'n', meaning: 'cấu trúc', example: 'Structures for social workers.', note: 'Bộ máy tổ chức.' },
  { word: 'commit', pos: 'v', meaning: 'cam kết', example: 'Committed to maximising wellbeing.', note: 'Hứa hẹn thực hiện mạnh mẽ.' },
  { word: 'maximize', pos: 'v', meaning: 'tối đa hóa', example: 'Maximising the wellbeing of individuals.', note: 'Đẩy lên mức cực đại.' },
  { word: 'wellbeing', pos: 'n', meaning: 'sự an sinh, phúc lợi', example: 'The wellbeing of communities.', note: 'Tình trạng hạnh phúc khỏe mạnh.' },
  { word: 'consider', pos: 'v', meaning: 'xem xét, coi là', example: 'We consider that wellbeing is vital.', note: 'Nhận định chủ quan cá nhân.' },
  { word: 'underpin', pos: 'v', meaning: 'củng cố, làm nền tảng', example: 'Underpinned by socially inclusive communities.', note: 'Tạo cơ sở cho cái gì.' },
  { word: 'inclusive', pos: 'adj', meaning: 'hòa nhập, bao hàm toàn diện', example: 'Socially inclusive communities.', note: 'Không bài xích sự khác biệt.' },
  { word: 'emphasize', pos: 'v', meaning: 'nhấn mạnh', example: 'Emphasise principles of social justice.', note: 'Tôn trọng điểm cốt lõi.' },
  { word: 'principle', pos: 'n', meaning: 'nguyên tắc', example: 'Principles of social justice.', note: 'Luật lệ cơ bản.' },
  { word: 'justice', pos: 'n', meaning: 'sự công bằng', example: 'Social justice is crucial.', note: 'Bảo vệ quyền lợi bình đẳng.' },
  { word: 'respect', pos: 'n, v', meaning: 'sự tôn trọng', example: 'Respect for human dignity.', note: 'Biểu hiện sự coi trọng.' },
  { word: 'dignity', pos: 'n', meaning: 'phẩm giá', example: 'Human dignity and human rights.', note: 'Giá trị bản thân thiêng liêng.' },
  { word: 'right', pos: 'n', meaning: 'quyền', example: 'Human rights are protected.', note: 'Lợi ích hợp pháp của con người.' },
  { word: 'value', pos: 'n', meaning: 'giá trị', example: 'These values are in accord.', note: 'Tiêu chuẩn tốt đẹp.' },
  { word: 'accord', pos: 'n', meaning: 'sự hài hòa, đồng thuận', example: 'In complete accord with the movement.', note: 'Phù hợp chặt chẽ.' },
  { word: 'movement', pos: 'n', meaning: 'phong trào', example: 'The disability advocacy movement.', note: 'Tập thể có khuynh hướng tư tưởng.' },
  { word: 'convention', pos: 'n', meaning: 'công ước', example: 'The United Nations Convention.', note: 'Bản cam kết văn bản luật.' },
  { word: 'inform', pos: 'v', meaning: 'thông báo, định hướng', example: 'These principles inform the NDIS.', note: 'Cung cấp nền móng thông tin.' },
  { word: 'prioritize', pos: 'v', meaning: 'ưu tiên', example: 'Social workers prioritise understanding.', note: 'Xếp lên hàng đầu.' },
  { word: 'holistic', pos: 'adj', meaning: 'toàn diện', example: 'A holistic understanding of the person.', note: 'Góc nhìn đa chiều.' },
  { word: 'impairment', pos: 'n', meaning: 'sự suy yếu, sự tổn thương/khiếm khuyết thể chất', example: 'Seeing their impairment as only one aspect.', note: 'Sự giảm chức năng vốn có của cơ thể.' },
  { word: 'aspect', pos: 'n', meaning: 'khía cạnh', example: 'One aspect of what makes them who they are.', note: 'Nét đặc điểm.' },
  { word: 'drive', pos: 'v', meaning: 'thúc đẩy, dắt dẫn', example: 'This view is driven by deep belief.', note: 'Làm nội lực phát triển.' },
  { word: 'belief', pos: 'n', meaning: 'đức tin, niềm tin', example: 'A deep belief in human worth.', note: 'Sự tin tưởng tuyệt đối.' },
  { word: 'intrinsic', pos: 'adj', meaning: 'thuộc về bản chất, 내 tại', example: 'The intrinsic worth of human beings.', note: 'Bên trong không đổi được.' },
  { word: 'worth', pos: 'n', meaning: 'giá trị bản thân', example: 'Intrinsic worth.', note: 'Khía cạnh đạo đức con người.' },
  { word: 'inalienable', pos: 'adj', meaning: 'không thể tước đoạt', example: 'Inalienable right to dignity.', note: 'Là quyền bất khả xâm phạm.' },
  { word: 'determination', pos: 'n', meaning: 'quyết tâm, tự quyết', example: 'Right to self-determination.', note: 'Nỗ lực và quyền làm chủ.' },
  { word: 'draw', pos: 'v', meaning: 'dựa vào, rút ra', example: 'Drawing on the significant contribution.', note: 'Bắt nguồn ý tưởng.' },
  { word: 'significant', pos: 'adj', meaning: 'quan trọng, đáng kể', example: 'The significant contribution of advocacy.', note: 'Đóng vai trò cực lớn.' },
  { word: 'diverse', pos: 'adj', meaning: 'đa dạng', example: 'People with disability are a diverse group.', note: 'Nhiều phân khúc khác nhau.' },
  { word: 'experience', pos: 'n', meaning: 'trải nghiệm', example: 'Wide range of experiences.', note: 'Thực tiễn quá khứ.' },
  { word: 'potential', pos: 'n, adj', meaning: 'tiềm năng', example: 'Potential for development.', note: 'Năng lực ngầm.' },
  { word: 'development', pos: 'n', meaning: 'sự phát triển', example: 'Focusing on their development.', note: 'Quá trình đi lên.' },
  { word: 'distinction', pos: 'n', meaning: 'sự phân biệt', example: 'A distinction between impairment and disability.', note: 'Chỉ ra ranh giới khác nhau.' },
  { word: 'capacity', pos: 'n', meaning: 'năng lực, khả năng', example: 'Differences in capacity.', note: 'Khả năng chứa hoặc thực hiện.' },
  { word: 'difficulty', pos: 'n', meaning: 'sự khó khăn', example: 'Cause difficulty in everyday functioning.', note: 'Rào cản chướng ngại.' },
  { word: 'everyday', pos: 'adj', meaning: 'hàng ngày', example: 'Everyday functioning.', note: 'Thường xuyên và bình dị.' },
  { word: 'function', pos: 'v, n', meaning: 'chức năng, hoạt động', example: 'Everyday functioning is impacted.', note: 'Sự hoạt động sinh lý bình thường.' },
  { word: 'represent', pos: 'v', meaning: 'đại diện cho', example: 'Disability represents a complex interaction.', note: 'Làm khuôn mẫu.' },
  { word: 'larger', pos: 'adj', meaning: 'rộng lớn hơn', example: 'The larger interaction with society.', note: 'Cấp độ vĩ mô.' },
  { word: 'complex', pos: 'adj', meaning: 'phức tạp', example: 'A complex interaction.', note: 'Giao thoa nhiều khía cạnh.' },
  { word: 'process', pos: 'n', meaning: 'quá trình', example: 'Structures and processes of society.', note: 'Quy trình vận hành.' },
  { word: 'adopt', pos: 'v', meaning: 'áp dụng, nhận nuôi', example: 'Adopt a person-in-environment approach.', note: 'Lấy làm phương pháp hành động.' },
  { word: 'approach', pos: 'n', meaning: 'cách tiếp cận', example: 'Person-in-environment approach.', note: 'Chiến thuật phương hướng.' },
  { word: 'focus', pos: 'n, v', meaning: 'sự tập trung', example: 'A focus on structural factors.', note: 'Nhắm mũi nhọn vào đâu.' },
  { word: 'structural', pos: 'adj', meaning: 'thuộc thẩm quyền cấu trúc', example: 'Cultural and structural factors.', note: 'Liên quan bộ máy cứng.' },
  { word: 'impact', pos: 'v, n', meaning: 'tác động', example: 'Factors that negatively impact an individual.', note: 'Tạo nên hệ ứng ngoại vi.' },
  { word: 'engage', pos: 'v', meaning: 'tham gia, gắn kết', example: 'Ability to engage with the social world.', note: 'Có tính cộng đồng.' },
  { word: 'maintain', pos: 'v', meaning: 'duy trì', example: 'Focus on maintaining quality of life.', note: 'Giữ nguyên hiện trạng tốt.' },
  { word: 'quality', pos: 'n', meaning: 'chất lượng', example: 'Quality of life is an indicator.', note: 'Mức độ tốt/giỏi.' },
  { word: 'life', pos: 'n', meaning: 'cuộc sống', example: 'Life needs of people.', note: 'Toàn bộ sinh mệnh.' },
  { word: 'contribute', pos: 'v', meaning: 'đóng góp', example: 'We contribute knowledge and skills.', note: 'Mang tới lợi ích.' },
  { word: 'design', pos: 'n, v', meaning: 'sự thiết kế', example: 'Program design and planning.', note: 'Lập sơ đồ quy hoạch.' },
  { word: 'planning', pos: 'n', meaning: 'việc lập kế hoạch', example: 'Individual planning is important.', note: 'Hành động vạch định tương lai.' },
  { word: 'expand', pos: 'v', meaning: 'mở rộng', example: 'NDIS is expanding the range of roles.', note: 'Lan rộng không gian hoặc quy mô.' },
  { word: 'expertise', pos: 'n', meaning: 'chuyên môn sâu', example: 'Social workers have the expertise to fill roles.', note: 'Phẩm chất tay nghề cao.' },
  { word: 'fill', pos: 'v', meaning: 'đảm nhiệm, lấp đầy', example: 'Expertise to fill specific roles.', note: 'Nhận vị trí bỏ trống.' },
  { word: 'local', pos: 'adj', meaning: 'địa phương', example: 'Local area coordinators.', note: 'Trong khu vực sinh sống.' },
  { word: 'area', pos: 'n', meaning: 'khu vực, mảng', example: 'Local area planners.', note: 'Một vị trí ranh giới địa lý.' },
  { word: 'coordinator', pos: 'n', meaning: 'điều phối viên', example: 'Service coordinators manage teams.', note: 'Nghề chuyên liên kết dịch vụ.' },
  { word: 'planner', pos: 'n', meaning: 'người lập kế hoạch', example: 'Coordinators and planners.', note: 'Nhân sư chuyên làm plan.' },
  { word: 'service', pos: 'n', meaning: 'dịch vụ', example: 'Disability service providers.', note: 'Hỗ trợ không phải sản phẩm cứng.' },
  { word: 'provider', pos: 'n', meaning: 'nhà cung cấp', example: 'Working alongside service providers.', note: 'Thường là cơ quan dịch vụ xã hội.' },
  { word: 'healthcare', pos: 'n', meaning: 'chăm sóc sức khỏe', example: 'All levels of healthcare.', note: 'Ngành y tế.' },
  { word: 'early', pos: 'adj', meaning: 'sớm', example: 'Early intervention services.', note: 'Đầu giai đoạn.' },
  { word: 'rehabilitation', pos: 'n', meaning: 'sự phục hồi chức năng', example: 'Rehabilitation services for disabled.', note: 'Hồi phục lại năng lực ban đầu.' },
  { word: 'aged', pos: 'adj', meaning: 'người già, có tuổi', example: 'Aged care focuses on seniors.', note: 'Loại hình dịch vụ an sinh cho người lớn tuổi.' },
  { word: 'care', pos: 'n', meaning: 'sự chăm sóc', example: 'Aged care and mental health.', note: 'Hành động trông nom hộ thân.' },
  { word: 'homelessness', pos: 'n', meaning: 'tình trạng vô gia cư', example: 'Homelessness services in cities.', note: 'Vấn nạn không có nhà ở hợp pháp.' },
  { word: 'protection', pos: 'n', meaning: 'sự bảo vệ', example: 'Child protection is critical.', note: 'Cục bảo vệ trẻ em (Child Protection).' },
  { word: 'strength', pos: 'n', meaning: 'điểm mạnh', example: 'Community strengths and needs.', note: 'Khía cạnh lợi thế nội lực.' },
  { word: 'need', pos: 'n', meaning: 'nhu cầu', example: 'Addressing the needs of the individual.', note: 'Trạng thái cần được hỗ trợ.' },
  { word: 'collaboratively', pos: 'adv', meaning: 'một cách phối hợp', example: 'Work collaboratively to support people.', note: 'Làm việc theo khuôn mẫu đồng đội.' },
  { word: 'support', pos: 'v', meaning: 'hỗ trợ', example: 'Support people to achieve their lives.', note: 'Cung cấp sức lực.' },
  { word: 'lifespan', pos: 'n', meaning: 'vòng đời', example: 'Our practice is across the lifespan.', note: 'Khoảng thời gian trường tồn.' },
  { word: 'span', pos: 'v', meaning: 'trải dài qua', example: 'Social work practice spans a number of approaches.', note: 'Từ này bao hàm nghĩa phủ rộng.' },
  { word: 'number', pos: 'n', meaning: 'một lượng, một số lượng', example: 'A number of approaches.', note: 'Đếm được.' },
  { word: 'psychosocial', pos: 'adj', meaning: 'thuộc tâm lý xã hội', example: 'Psychosocial assessment is required.', note: 'Kết hợp Psychological và Social.' },
  { word: 'risk', pos: 'n', meaning: 'sự rủi ro', example: 'Risk assessment.', note: 'Bài toán lường trước bất trắc.' },
  { word: 'build', pos: 'v', meaning: 'xây dựng', example: 'Capacity building initiatives.', note: 'Tạo lập nền tảng.' },
  { word: 'educate', pos: 'v', meaning: 'giáo dục', example: 'Educate and consult the community.', note: 'Đồng nghĩa: teach.' },
  { word: 'consult', pos: 'v', meaning: 'hội ý tư vấn', example: 'Consult with local community groups.', note: 'Hỏi hoặc đưa lời xúi.' },
  { word: 'navigate', pos: 'v', meaning: 'điều hướng, lèo lái', example: 'Navigate health and welfare systems.', note: 'Khả năng hiểu cách thức đường đi hệ thống.' },
  { word: 'welfare', pos: 'n', meaning: 'phúc lợi', example: 'The welfare system helps citizens.', note: 'An sinh tài chính / sức khỏe từ chính phủ.' },
  { word: 'brokerage', pos: 'n', meaning: 'sự tư vấn trung gian', example: 'Service brokerage for clients.', note: 'Hành động trung gian thu xếp dịch vụ.' },
  { word: 'referral', pos: 'n', meaning: 'giấy giới thiệu, công văn chỉ dẫn', example: 'Referrals to other services.', note: 'Văn bản ủy quyền đưa thân chủ tới cơ quan.' },
  { word: 'organizational', pos: 'adj', meaning: 'thuộc về tổ chức', example: 'Organizational and systemic level.', note: 'Tổ chức bộ máy.' },
  { word: 'systemic', pos: 'adj', meaning: 'thuộc hệ thống toàn diện', example: 'Advocating for systemic change.', note: 'Khác biệt với systematic (có tính phân loại).' },
  { word: 'level', pos: 'n', meaning: 'cấp độ', example: 'Systemic level changes.', note: 'Độ cao vĩ mô/vi mô định lượng.' },
  { word: 'grief', pos: 'n', meaning: 'sự đau buồn', example: 'Dealing with grief and loss.', note: 'Thường gặp trong tham vấn gia đình/bện tật.' },
  { word: 'loss', pos: 'n', meaning: 'sự mất mát', example: 'Grief and loss are hard to overcome.', note: 'Khi có biến cố xảy ra.' },
  { word: 'complex', pos: 'adj', meaning: 'phức tạp', example: 'Consider the complexity involved.', note: 'Rắc rối, phi tuyến tính.' },
  { word: 'complexity', pos: 'n', meaning: 'tính phức tạp', example: 'Complexity of multiple perspectives.', note: 'Nhiều lớp đa chiều gộp lại.' },
  { word: 'perspective', pos: 'n', meaning: 'góc nhìn', example: 'From multiple perspectives.', note: 'Bảo đàm quan điểm khách quan.' },
  { word: 'appropriate', pos: 'adj', meaning: 'phù hợp', example: 'Providing appropriate services.', note: 'Đồng nghĩa: suitable, correct.' },
  { word: 'targeted', pos: 'adj', meaning: 'có mục tiêu định hướng', example: 'Targeted services specifically for them.', note: 'Đánh trúng đối tượng.' },
  { word: 'meet', pos: 'v', meaning: 'đáp ứng', example: 'To meet the whole life needs.', note: 'Meet criteria / needs / goals.' },
  { word: 'whole', pos: 'adj', meaning: 'toàn bộ', example: 'Whole of life needs.', note: 'Kinh điển cho từ all.' },
  { word: 'multi-focused', pos: 'adj', meaning: 'đa mục tiêu', example: 'A multi-focused approach.', note: 'Có thể bao hàm nhiều phương diện.' },
  { word: 'socioeconomic', pos: 'adj', meaning: 'thuộc về kinh tế và xã hội', example: 'Socioeconomic backgrounds.', note: 'Nền tảng giai cấp và tiền bạc.' },
  { word: 'legal', pos: 'adj', meaning: 'thuộc luật pháp', example: 'Legal and cultural factors.', note: 'Ví dụ: Đạo luật NDIS.' },
  { word: 'interact', pos: 'v', meaning: 'tương tác', example: 'How these factors interact.', note: 'Tác động lẫn nhau.' },
  { word: 'produce', pos: 'v', meaning: 'tạo ra', example: 'Impact to produce the stigma.', note: 'Đẻ ra hậu quả.' },
  { word: 'stigma', pos: 'n', meaning: 'sự kỳ thị', example: 'Mental illness often carries a stigma.', note: 'Thành kiến xấu.' },
  { word: 'discrimination', pos: 'n', meaning: 'sự phân biệt đối xử', example: 'Discrimination based on race.', note: 'Đối đãi bất công.' },
  { word: 'marginalization', pos: 'n', meaning: 'sự cho ra rìa', example: 'Marginalisation of minority groups.', note: 'Hiện tượng đẩy một thế lực ra vùng ven xã hội.' },
  { word: 'isolation', pos: 'n', meaning: 'sự cô lập', example: 'Social isolation is dangerous.', note: 'Không có vòng tay cộng đồng hỗ trợ.' },
  { word: 'experience', pos: 'v', meaning: 'hứng chịu, trải qua', example: 'Isolation experienced by many individuals.', note: 'Bị tác động.' },
  { word: 'conclusion', pos: 'n', meaning: 'kết luận', example: 'In conclusion, we need change.', note: 'Phần tổng kết.' },
  { word: 'emerge', pos: 'v', meaning: 'nổi lên, xuất hiện', example: 'The emerging private sector.', note: 'Lên hương, mới mọc.' },
  { word: 'emerging', pos: 'adj', meaning: 'đang chớm nở', example: 'Emerging private sector for NDIS.', note: 'Tính từ mô phỏng xu hướng kinh doanh mới.' },
  { word: 'private', pos: 'adj', meaning: 'tư nhân', example: 'Private sector provides alternatives.', note: 'Tổ chức phi nhà nước.' },
  { word: 'sector', pos: 'n', meaning: 'khu vực kinh tế/ban ngành', example: 'Government and private sector.', note: 'Nhóm các công ty cung cấp dịch vụ chung mảng.' },
  { word: 'valuable', pos: 'adj', meaning: 'giá trị, quý giá', example: 'A valuable contribution.', note: 'Mang nhiều ý nghĩa hữu hình/vô hình.' }
];
