export const VOCABULARY_LIST = [
  { word: "Attainment", pos: "Noun", meaning: "Sự đạt được/thành tựu", example: "The attainment of competence.", note: "Từ gốc: attain" },
  { word: "Intervene", pos: "Verb", meaning: "Can thiệp", example: "Developing intervention strategies.", note: "Noun: intervention" },
  { word: "Alleviate", pos: "Verb", meaning: "Làm nhẹ bớt", example: "Alleviating family stress.", note: "Đồng nghĩa: relieve, ease" },
  { word: "Liaison", pos: "Noun", meaning: "Liên lạc/Mối liên kết", example: "School-Community Liaison.", note: "Dễ sai chính tả" },
  { word: "Truancy", pos: "Noun", meaning: "Sự trốn học", example: "Programs for truants.", note: "Truant (người)" },
  { word: "Competence", pos: "Noun", meaning: "Năng lực", example: "Attainment of competence.", note: "Adj: competent" },
  { word: "Facilitate", pos: "Verb", meaning: "Tạo điều kiện", example: "Facilitate support.", note: "Hỗ trợ tiến trình" },
  { word: "Assessment", pos: "Noun", meaning: "Đánh giá", example: "Special Education Assessment.", note: "Verb: assess" },
  { word: "Collaboration", pos: "Noun", meaning: "Hợp tác", example: "Collaboration is key.", note: "Làm việc chung" },
  { word: "Interfere", pos: "Verb", meaning: "Cản trở", example: "Interfere with learning.", note: "Luôn đi với 'with'" },
  { word: "Personnel", pos: "Noun", meaning: "Nhân sự", example: "School Personnel.", note: "Dễ nhầm với Personal" },
  { word: "Mobilize", pos: "Verb", meaning: "Huy động", example: "Mobilizing resources.", note: "Huy động nguồn lực" },
  { word: "Societal", pos: "Adjective", meaning: "Thuộc xã hội", example: "Societal forces.", note: "Từ Society" },
  { word: "Familial", pos: "Adjective", meaning: "Thuộc gia đình", example: "Familial factors.", note: "Từ Family" },
  { word: "Compliance", pos: "Noun", meaning: "Tuân thủ", example: "Compliance with law.", note: "Verb: comply with" },
  { word: "Hello", pos: "Greeting", meaning: "Xin chào", example: "Hello, how are you?", note: "Từ chào hỏi cơ bản nhất" },
  { word: "Goodbye", pos: "Greeting", meaning: "Tạm biệt", example: "Goodbye, see you later.", note: "Chào khi rời đi" },
  { word: "Please", pos: "Adverb", meaning: "Làm ơn", example: "Please help me.", note: "Dùng để yêu cầu lịch sự" },
  { word: "Thank", pos: "Verb", meaning: "Cảm ơn", example: "Thank you very much.", note: "Lời cảm ơn" },
  { word: "Sorry", pos: "Adjective", meaning: "Xin lỗi", example: "I am sorry.", note: "Dùng khi nhận lỗi" },
  { word: "Yes", pos: "Adverb", meaning: "Vâng, có", example: "Yes, I agree.", note: "Đồng ý" },
  { word: "No", pos: "Adverb", meaning: "Không", example: "No, thank you.", note: "Từ chối" },
  { word: "Excuse", pos: "Verb", meaning: "Xin lỗi (để làm phiền)", example: "Excuse me.", note: "Dùng khi muốn gây chú ý" },
  { word: "Time", pos: "Noun", meaning: "Thời gian", example: "What time is it?", note: "Khái niệm thời gian" },
  { word: "Year", pos: "Noun", meaning: "Năm", example: "Happy new year.", note: "Đv đo thời gian" },
  { word: "Month", pos: "Noun", meaning: "Tháng", example: "The month of May.", note: "12 tháng trong năm" },
  { word: "Day", pos: "Noun", meaning: "Ngày", example: "Have a good day.", note: "1 ngày = 24h" },
  { word: "Week", pos: "Noun", meaning: "Tuần", example: "Next week.", note: "1 tuần = 7 ngày" },
  { word: "Today", pos: "Noun", meaning: "Hôm nay", example: "Today is Monday.", note: "Thời điểm hiện tại" },
  { word: "Tomorrow", pos: "Noun", meaning: "Ngày mai", example: "See you tomorrow.", note: "Tương lai gần" },
  { word: "Yesterday", pos: "Noun", meaning: "Hôm qua", example: "I went yesterday.", note: "Quá khứ gần" },
  { word: "Hour", pos: "Noun", meaning: "Giờ", example: "One hour left.", note: "1 giờ = 60 phút" },
  { word: "Minute", pos: "Noun", meaning: "Phút", example: "Just a minute.", note: "1 phút = 60 giây" },
  { word: "Second", pos: "Noun", meaning: "Giây / Thứ hai", example: "Wait a second.", note: "Nhiều nghĩa" },
  { word: "Now", pos: "Adverb", meaning: "Bây giờ", example: "Do it now.", note: "Thời điểm này" },
  { word: "Thing", pos: "Noun", meaning: "Thứ, đồ vật", example: "What is this thing?", note: "Từ chung chung" },
  { word: "Man", pos: "Noun", meaning: "Đàn ông", example: "A good man.", note: "Số nhiều: men" },
  { word: "Woman", pos: "Noun", meaning: "Phụ nữ", example: "A beautiful woman.", note: "Số nhiều: women" },
  { word: "Child", pos: "Noun", meaning: "Trẻ em", example: "A sweet child.", note: "Số nhiều: children" },
  { word: "World", pos: "Noun", meaning: "Thế giới", example: "Around the world.", note: "Trái đất, toàn cầu" },
  { word: "Life", pos: "Noun", meaning: "Cuộc sống", example: "Life is beautiful.", note: "Số nhiều: lives" },
  { word: "Hand", pos: "Noun", meaning: "Bàn tay", example: "Hold my hand.", note: "Bộ phận cơ thể" },
  { word: "Part", pos: "Noun", meaning: "Phần, bộ phận", example: "Part of the team.", note: "Một mảng của tổng thể" },
  { word: "Eye", pos: "Noun", meaning: "Mắt", example: "Open your eyes.", note: "Bộ phận nhìn" },
  { word: "Place", pos: "Noun", meaning: "Địa điểm", example: "A nice place.", note: "Nơi chốn" },
  { word: "Work", pos: "Noun/Verb", meaning: "Công việc / Làm việc", example: "I go to work.", note: "Hoạt động sinh nhai" },
  { word: "Case", pos: "Noun", meaning: "Trường hợp / Vụ án", example: "In this case.", note: "Tình huống" },
  { word: "Point", pos: "Noun", meaning: "Điểm / Ý chính", example: "What's the point?", note: "Nhiều nghĩa" },
  { word: "Company", pos: "Noun", meaning: "Công ty", example: "A tech company.", note: "Nơi kinh doanh" },
  { word: "Family", pos: "Noun", meaning: "Gia đình", example: "My family.", note: "Tổ ấm" },
  { word: "Problem", pos: "Noun", meaning: "Vấn đề", example: "No problem.", note: "Rắc rối cần giải quyết" },
  { word: "Fact", pos: "Noun", meaning: "Sự thật", example: "In fact.", note: "Chân lý" },
  { word: "Be", pos: "Verb", meaning: "Thì, là, ở", example: "To be or not to be.", note: "Động từ tobe" },
  { word: "Have", pos: "Verb", meaning: "Có", example: "I have a pen.", note: "Sở hữu" },
  { word: "Do", pos: "Verb", meaning: "Làm", example: "Just do it.", note: "Hành động chung" },
  { word: "Say", pos: "Verb", meaning: "Nói", example: "Say a word.", note: "Phát ngôn" },
  { word: "Get", pos: "Verb", meaning: "Nhận, lấy", example: "Get it done.", note: "Đa nghĩa" },
  { word: "Make", pos: "Verb", meaning: "Làm, chế tạo", example: "Make a cake.", note: "Tạo ra cái mới" },
  { word: "Go", pos: "Verb", meaning: "Đi", example: "Let's go.", note: "Di chuyển" },
  { word: "Know", pos: "Verb", meaning: "Biết", example: "I don't know.", note: "Nhận thức" },
  { word: "Take", pos: "Verb", meaning: "Cầm, nắm, lấy", example: "Take my hand.", note: "Thao tác tay" },
  { word: "See", pos: "Verb", meaning: "Nhìn thấy", example: "I see you.", note: "Thị giác" },
  { word: "Come", pos: "Verb", meaning: "Đến", example: "Come here.", note: "Hướng về người nói" },
  { word: "Think", pos: "Verb", meaning: "Nghĩ", example: "I think so.", note: "Hoạt động não" },
  { word: "Look", pos: "Verb", meaning: "Nhìn", example: "Look at me.", note: "Hướng mắt về" },
  { word: "Want", pos: "Verb", meaning: "Muốn", example: "I want a car.", note: "Sự mong mỏi" },
  { word: "Give", pos: "Verb", meaning: "Cho", example: "Give me that.", note: "Chuyển giao" },
  { word: "Use", pos: "Verb", meaning: "Sử dụng", example: "Use your brain.", note: "Dùng công cụ" },
  { word: "Find", pos: "Verb", meaning: "Tìm thấy", example: "Find the key.", note: "Khám phá ra" },
  { word: "Tell", pos: "Verb", meaning: "Kể, bảo", example: "Tell a story.", note: "Giao tiếp" },
  { word: "Ask", pos: "Verb", meaning: "Hỏi, yêu cầu", example: "Ask a question.", note: "Gợi sự trả lời" },
  { word: "Work", pos: "Verb", meaning: "Làm việc", example: "I work hard.", note: "Lao động" },
  { word: "Seem", pos: "Verb", meaning: "Có vẻ", example: "It seems good.", note: "Cảm nhận" },
  { word: "Feel", pos: "Verb", meaning: "Cảm thấy", example: "I feel sick.", note: "Giác quan / Cảm xúc" },
  { word: "Try", pos: "Verb", meaning: "Cố gắng / Thử", example: "Try your best.", note: "Nỗ lực" },
  { word: "Leave", pos: "Verb", meaning: "Rời đi", example: "Leave me alone.", note: "Đi khỏi" },
  { word: "Call", pos: "Verb", meaning: "Gọi", example: "Call me later.", note: "Liên lạc" },
  { word: "Good", pos: "Adjective", meaning: "Tốt", example: "Good morning.", note: "Trạng thái tích cực" },
  { word: "New", pos: "Adjective", meaning: "Mới", example: "A new car.", note: "Chưa từng dùng" },
  { word: "First", pos: "Adjective", meaning: "Đầu tiên", example: "First time.", note: "Số thứ tự 1" },
  { word: "Last", pos: "Adjective", meaning: "Cuối cùng", example: "Last night.", note: "Cuối, trước đó" },
  { word: "Long", pos: "Adjective", meaning: "Dài", example: "A long way.", note: "Độ dài/thời gian" },
  { word: "Great", pos: "Adjective", meaning: "Tuyệt vời", example: "Great job.", note: "Rất tốt" },
  { word: "Little", pos: "Adjective", meaning: "Nhỏ, ít", example: "A little bit.", note: "Kích thước/số lượng" },
  { word: "Own", pos: "Adjective", meaning: "Của riêng", example: "My own house.", note: "Sở hữu nhấn mạnh" },
  { word: "Other", pos: "Adjective", meaning: "Khác", example: "Other people.", note: "Cái khác" },
  { word: "Old", pos: "Adjective", meaning: "Già, cũ", example: "An old man.", note: "Tuổi tác" },
  { word: "Right", pos: "Adjective", meaning: "Đúng / Phải", example: "You are right.", note: "Trái với sai / trái" },
  { word: "Big", pos: "Adjective", meaning: "To lớn", example: "A big tree.", note: "Kích thước" },
  { word: "High", pos: "Adjective", meaning: "Cao", example: "High jumps.", note: "Chiều cao" },
  { word: "Different", pos: "Adjective", meaning: "Khác biệt", example: "Different colors.", note: "Sự phân biệt" },
  { word: "Small", pos: "Adjective", meaning: "Nhỏ", example: "A small dog.", note: "Kích thước" },
  { word: "Large", pos: "Adjective", meaning: "Rộng lớn", example: "A large room.", note: "Quy mô" },
  { word: "Next", pos: "Adjective", meaning: "Tiếp theo", example: "Next year.", note: "Thời gian tới" },
  { word: "Early", pos: "Adjective", meaning: "Sớm", example: "Early bird.", note: "Trước thời hạn" },
  { word: "Young", pos: "Adjective", meaning: "Trẻ", example: "A young lady.", note: "Tuổi nhỏ" },
  { word: "Important", pos: "Adjective", meaning: "Quan trọng", example: "Important point.", note: "Cần thiết" },
  { word: "Few", pos: "Adjective", meaning: "Ít", example: "A few days.", note: "Số lượng nhỏ" },
  { word: "Public", pos: "Adjective", meaning: "Công cộng", example: "Public school.", note: "Cho mọi người" },
  { word: "Bad", pos: "Adjective", meaning: "Tồi, xấu", example: "Bad weather.", note: "Phản nghĩa của Good" },
  { word: "Same", pos: "Adjective", meaning: "Giống nhau", example: "The same day.", note: "Đồng nhất" },
  { word: "Able", pos: "Adjective", meaning: "Có khả năng", example: "Able to do it.", note: "Năng lực" },
  { word: "Up", pos: "Preposition", meaning: "Lên", example: "Go up.", note: "Hướng lên" },
  { word: "Down", pos: "Preposition", meaning: "Xuống", example: "Sit down.", note: "Hướng xuống" },
  { word: "In", pos: "Preposition", meaning: "Trong", example: "In the room.", note: "Vị trí bên trong" },
  { word: "Out", pos: "Preposition", meaning: "Ngoài", example: "Go out.", note: "Vị trí ngoài" },
  { word: "On", pos: "Preposition", meaning: "Trên", example: "On the table.", note: "Bề mặt" },
  { word: "Off", pos: "Preposition", meaning: "Tắt / Rời khỏi", example: "Turn off.", note: "Ngắt kết nối" },
  { word: "Over", pos: "Preposition", meaning: "Quá / Chéo qua", example: "Over there.", note: "Phía tính" },
  { word: "Under", pos: "Preposition", meaning: "Dưới", example: "Under the sea.", note: "Vị trí thấp hơn" },
  { word: "Again", pos: "Adverb", meaning: "Lại", example: "Do it again.", note: "Lặp lại" },
  { word: "Further", pos: "Adverb", meaning: "Xa hơn", example: "Further info.", note: "Cấp độ hơn" },
  { word: "Then", pos: "Adverb", meaning: "Sau đó", example: "And then?", note: "Kế tiếp" },
  { word: "Once", pos: "Adverb", meaning: "Một lần", example: "Once a day.", note: "Số lần" },
  { word: "Here", pos: "Adverb", meaning: "Ở đây", example: "Come here.", note: "Vị trí gần" },
  { word: "There", pos: "Adverb", meaning: "Ở đó", example: "Go there.", note: "Vị trí xa" },
  { word: "When", pos: "Adverb", meaning: "Khi nào", example: "When is it?", note: "Hỏi thời gian" },
  { word: "Where", pos: "Adverb", meaning: "Ở đâu", example: "Where are you?", note: "Hỏi nơi chốn" },
  { word: "Why", pos: "Adverb", meaning: "Tại sao", example: "Why so sad?", note: "Hỏi lý do" },
  { word: "How", pos: "Adverb", meaning: "Thế nào", example: "How to fix this?", note: "Hỏi cách thức" },
  { word: "All", pos: "Pronoun", meaning: "Tất cả", example: "All of us.", note: "Toàn bộ" },
  { word: "Any", pos: "Pronoun", meaning: "Bất kỳ", example: "Any idea?", note: "Dùng trong câu phủ định/hỏi" },
  { word: "Both", pos: "Pronoun", meaning: "Cả hai", example: "Both of them.", note: "2 đối tượng" },
  { word: "Each", pos: "Pronoun", meaning: "Mỗi", example: "Each person.", note: "Từng cá thể" },
  { word: "Always", pos: "Adverb", meaning: "Luôn luôn", example: "Always smiling.", note: "Tần suất 100%" },
  { word: "Usually", pos: "Adverb", meaning: "Thường xuyên", example: "I usually read.", note: "Tần suất cao" },
  { word: "Often", pos: "Adverb", meaning: "Thường", example: "How often?", note: "Nhiều lần" },
  { word: "Sometimes", pos: "Adverb", meaning: "Thỉnh thoảng", example: "Sometimes I cry.", note: "Tần suất 50%" },
  { word: "Rarely", pos: "Adverb", meaning: "Hiếm khi", example: "Rarely late.", note: "Rất ít khi" },
  { word: "Never", pos: "Adverb", meaning: "Không bao giờ", example: "Never give up.", note: "Tần suất 0%" },
  { word: "Very", pos: "Adverb", meaning: "Rất", example: "Very good.", note: "Mức độ cao" },
  { word: "Too", pos: "Adverb", meaning: "Quá / Cũng vậy", example: "Me too.", note: "Nhấn mạnh" },
  { word: "Quite", pos: "Adverb", meaning: "Khá", example: "Quite nice.", note: "Mức độ vừa" },
  { word: "Really", pos: "Adverb", meaning: "Thật sự", example: "Really cold.", note: "Nhấn mạnh sự thật" },
  { word: "Just", pos: "Adverb", meaning: "Chỉ / Vừa mới", example: "Just do it.", note: "Nhấn mạnh hạn chế" },
  { word: "Only", pos: "Adverb", meaning: "Chỉ (duy nhất)", example: "Only you.", note: "Không còn khác" },
  { word: "Enough", pos: "Adverb", meaning: "Đủ", example: "Enough money.", note: "Đáp ứng yêu cầu" },
  { word: "Almost", pos: "Adverb", meaning: "Gần như", example: "Almost there.", note: "Suýt soát" },
  { word: "Even", pos: "Adverb", meaning: "Thậm chí", example: "Even harder.", note: "Mức độ bất ngờ" },
  { word: "Still", pos: "Adverb", meaning: "Vẫn", example: "Still working.", note: "Chưa thay đổi" },
  { word: "Much", pos: "Adjective", meaning: "Nhiều (ko đếm được)", example: "Much water.", note: "Đi với danh từ ko đếm được" },
  { word: "Many", pos: "Adjective", meaning: "Nhiều (đếm được)", example: "Many books.", note: "Đi với danh từ đếm được" },
  { word: "More", pos: "Adjective", meaning: "Nhiều hơn", example: "More time.", note: "So sánh hơn" },
  { word: "Most", pos: "Adjective", meaning: "Hầu hết / Nhất", example: "Most people.", note: "So sánh nhất" },
  { word: "Also", pos: "Adverb", meaning: "Cũng", example: "I also like it.", note: "Bổ sung thông tin" },
  { word: "Well", pos: "Adverb", meaning: "Tốt / Chà", example: "Well done.", note: "Trạng từ của Good" },
  { word: "Apple", pos: "Noun", meaning: "Quả táo", example: "Eat an apple.", note: "Trái cây" },
  { word: "Banana", pos: "Noun", meaning: "Quả chuối", example: "Yellow banana.", note: "Trái cây" },
  { word: "Water", pos: "Noun", meaning: "Nước", example: "Drink water.", note: "Đồ uống" },
  { word: "Bread", pos: "Noun", meaning: "Bánh mì", example: "Eat bread.", note: "Đồ ăn" },
  { word: "Milk", pos: "Noun", meaning: "Sữa", example: "Cow's milk.", note: "Đồ uống" },
  { word: "Cat", pos: "Noun", meaning: "Mèo", example: "A black cat.", note: "Động vật" },
  { word: "Dog", pos: "Noun", meaning: "Chó", example: "A loyal dog.", note: "Động vật" },
  { word: "Bird", pos: "Noun", meaning: "Chim", example: "Birds fly.", note: "Động vật" },
  { word: "Fish", pos: "Noun", meaning: "Cá", example: "Fish swim.", note: "Động vật" },
  { word: "Tree", pos: "Noun", meaning: "Cái cây", example: "Tall tree.", note: "Thực vật" },
  { word: "Flower", pos: "Noun", meaning: "Hoa", example: "Beautiful flower.", note: "Thực vật" },
  { word: "Sun", pos: "Noun", meaning: "Mặt trời", example: "The sun shines.", note: "Thiên thể" },
  { word: "Moon", pos: "Noun", meaning: "Mặt trăng", example: "The full moon.", note: "Thiên thể" },
  { word: "Star", pos: "Noun", meaning: "Ngôi sao", example: "Stars shine at night.", note: "Bầu trời" },
  { word: "Sky", pos: "Noun", meaning: "Bầu trời", example: "Blue sky.", note: "Tự nhiên" },
  { word: "Rain", pos: "Noun", meaning: "Mưa", example: "Heavy rain.", note: "Thời tiết" },
  { word: "Snow", pos: "Noun", meaning: "Tuyết", example: "White snow.", note: "Thời tiết" },
  { word: "Wind", pos: "Noun", meaning: "Gió", example: "Strong wind.", note: "Thời tiết" },
  { word: "Fire", pos: "Noun", meaning: "Lửa", example: "Hot fire.", note: "Tự nhiên" },
  { word: "House", pos: "Noun", meaning: "Ngôi nhà", example: "My house.", note: "Nơi ở" },
  { word: "Room", pos: "Noun", meaning: "Căn phòng", example: "Living room.", note: "Trong nhà" },
  { word: "Door", pos: "Noun", meaning: "Cửa ra vào", example: "Open the door.", note: "Trong nhà" },
  { word: "Window", pos: "Noun", meaning: "Cửa sổ", example: "Clean the window.", note: "Trong nhà" },
  { word: "Table", pos: "Noun", meaning: "Cái bàn", example: "On the table.", note: "Đồ nội thất" },
  { word: "Chair", pos: "Noun", meaning: "Cái ghế", example: "Sit on the chair.", note: "Đồ nội thất" },
  { word: "Bed", pos: "Noun", meaning: "Cái giường", example: "Go to bed.", note: "Phòng ngủ" },
  { word: "Book", pos: "Noun", meaning: "Sách", example: "Read a book.", note: "Học tập" },
  { word: "Pen", pos: "Noun", meaning: "Cái bút", example: "Write with a pen.", note: "Học tập" },
  { word: "Paper", pos: "Noun", meaning: "Giấy", example: "A piece of paper.", note: "Vật liệu" },
  { word: "School", pos: "Noun", meaning: "Trường học", example: "Go to school.", note: "Giáo dục" },
  { word: "Teacher", pos: "Noun", meaning: "Giáo viên", example: "My teacher.", note: "Giáo dục" },
  { word: "Student", pos: "Noun", meaning: "Học sinh", example: "Good student.", note: "Giáo dục" },
  { word: "Class", pos: "Noun", meaning: "Lớp học", example: "In class.", note: "Giáo dục" },
  { word: "Car", pos: "Noun", meaning: "Ô tô", example: "Drive a car.", note: "Phương tiện" },
  { word: "Bus", pos: "Noun", meaning: "Xe buýt", example: "Take the bus.", note: "Phương tiện" },
  { word: "Train", pos: "Noun", meaning: "Tàu hỏa", example: "By train.", note: "Phương tiện" },
  { word: "Plane", pos: "Noun", meaning: "Máy bay", example: "Fly a plane.", note: "Phương tiện" },
  { word: "Road", pos: "Noun", meaning: "Con đường", example: "On the road.", note: "Giao thông" },
  { word: "City", pos: "Noun", meaning: "Thành phố", example: "Big city.", note: "Địa điểm" },
  { word: "Country", pos: "Noun", meaning: "Quốc gia", example: "My country.", note: "Địa điểm" },
  { word: "Name", pos: "Noun", meaning: "Tên", example: "What is your name?", note: "Nhận dạng" },
  { word: "Friend", pos: "Noun", meaning: "Bạn bè", example: "My best friend.", note: "Mối quan hệ" },
  { word: "Money", pos: "Noun", meaning: "Tiền", example: "Need more money.", note: "Kinh tế" },
  { word: "Job", pos: "Noun", meaning: "Nghề nghiệp", example: "Good job.", note: "Công việc" },
  { word: "Happy", pos: "Adjective", meaning: "Vui vẻ", example: "I am happy.", note: "Cảm xúc" },
  { word: "Sad", pos: "Adjective", meaning: "Buồn", example: "Don't be sad.", note: "Cảm xúc" },
  { word: "Angry", pos: "Adjective", meaning: "Tức giận", example: "He is angry.", note: "Cảm xúc" },
  { word: "Tired", pos: "Adjective", meaning: "Mệt mỏi", example: "I feel tired.", note: "Cơ thể" },
  { word: "Hungry", pos: "Adjective", meaning: "Đói", example: "I am hungry.", note: "Cảm giác" },
  { word: "Thirsty", pos: "Adjective", meaning: "Khát", example: "Are you thirsty?", note: "Cảm giác" },
  { word: "Hot", pos: "Adjective", meaning: "Nóng", example: "Hot summer.", note: "Nhiệt độ" },
  { word: "Cold", pos: "Adjective", meaning: "Lạnh", example: "Cold winter.", note: "Nhiệt độ" },
  { word: "Fast", pos: "Adjective", meaning: "Nhanh", example: "Run fast.", note: "Tốc độ" },
  { word: "Slow", pos: "Adjective", meaning: "Chậm", example: "Move slow.", note: "Tốc độ" },
  { word: "Hard", pos: "Adjective", meaning: "Cứng / Khó", example: "Hard work.", note: "Nhiều nghĩa" },
  { word: "Soft", pos: "Adjective", meaning: "Mềm mại", example: "Soft bed.", note: "Chất liệu" },
  { word: "Easy", pos: "Adjective", meaning: "Dễ dàng", example: "Easy test.", note: "Độ khó" },
  { word: "Strong", pos: "Adjective", meaning: "Khỏe mạnh", example: "Strong boy.", note: "Sức mạnh" },
  { word: "Weak", pos: "Adjective", meaning: "Yếu đuối", example: "Feeling weak.", note: "Thiếu sức mạnh" },
  { word: "Beautiful", pos: "Adjective", meaning: "Xinh đẹp", example: "Beautiful girl.", note: "Ngoại hình" },
  { word: "Ugly", pos: "Adjective", meaning: "Xấu xí", example: "Ugly duckling.", note: "Ngoại hình" },
  { word: "Rich", pos: "Adjective", meaning: "Giàu có", example: "Rich man.", note: "Kinh tế" },
  { word: "Poor", pos: "Adjective", meaning: "Nghèo", example: "Poor family.", note: "Kinh tế" },
  { word: "Clean", pos: "Adjective", meaning: "Sạch sẽ", example: "Clean room.", note: "Vệ sinh" },
  { word: "Dirty", pos: "Adjective", meaning: "Bẩn thỉu", example: "Dirty hands.", note: "Vệ sinh" },
  { word: "Open", pos: "Adjective", meaning: "Mở", example: "Open door.", note: "Trạng thái" },
  { word: "Close", pos: "Verb", meaning: "Đóng", example: "Close the book.", note: "Hành động" },
  { word: "Buy", pos: "Verb", meaning: "Mua", example: "Buy food.", note: "Giao dịch" },
  { word: "Sell", pos: "Verb", meaning: "Bán", example: "Sell a car.", note: "Giao dịch" },
  { word: "Pay", pos: "Verb", meaning: "Trả tiền", example: "Pay the bill.", note: "Tài chính" },
  { word: "Play", pos: "Verb", meaning: "Chơi", example: "Play a game.", note: "Giải trí" },
  { word: "Watch", pos: "Verb", meaning: "Xem", example: "Watch TV.", note: "Hành động" },
  { word: "Listen", pos: "Verb", meaning: "Nghe", example: "Listen to music.", note: "Giác quan" },
  { word: "Hear", pos: "Verb", meaning: "Nghe thấy", example: "Can you hear?", note: "Giác quan" },
  { word: "Speak", pos: "Verb", meaning: "Nói (ngôn ngữ)", example: "Speak English.", note: "Giao tiếp" },
  { word: "Read", pos: "Verb", meaning: "Đọc", example: "Read a newspaper.", note: "Học tập" },
  { word: "Write", pos: "Verb", meaning: "Viết", example: "Write a letter.", note: "Học tập" },
  { word: "Learn", pos: "Verb", meaning: "Học", example: "Learn new things.", note: "Tiếp thu" },
  { word: "Teach", pos: "Verb", meaning: "Dạy", example: "Teach English.", note: "Giáo dục" },
  { word: "Walk", pos: "Verb", meaning: "Đi bộ", example: "Walk to work.", note: "Vận động" },
  { word: "Run", pos: "Verb", meaning: "Chạy", example: "Run away.", note: "Vận động" },
  { word: "Jump", pos: "Verb", meaning: "Nhảy", example: "Jump high.", note: "Vận động" },
  { word: "Sleep", pos: "Verb", meaning: "Ngủ", example: "Sleep well.", note: "Nghỉ ngơi" },
  { word: "Eat", pos: "Verb", meaning: "Ăn", example: "Eat lunch.", note: "Dinh dưỡng" },
  { word: "Drink", pos: "Verb", meaning: "Uống", example: "Drink juice.", note: "Dinh dưỡng" },
  { word: "Smile", pos: "Verb", meaning: "Mỉm cười", example: "She smiled.", note: "Cảm xúc" },
  { word: "Laugh", pos: "Verb", meaning: "Cười thành tiếng", example: "Laugh out loud.", note: "Vui vẻ" },
  { word: "Cry", pos: "Verb", meaning: "Khóc", example: "Don't cry.", note: "Nỗi buồn" },
  { word: "Love", pos: "Verb", meaning: "Yêu", example: "I love you.", note: "Tình cảm" },
  { word: "Hate", pos: "Verb", meaning: "Ghét", example: "Hate this weather.", note: "Cảm xúc" },
  { word: "Like", pos: "Verb", meaning: "Thích", example: "I like dogs.", note: "Sở thích" },
  { word: "Hope", pos: "Verb", meaning: "Hy vọng", example: "I hope so.", note: "Mong đợi" },
  { word: "Wish", pos: "Verb", meaning: "Ước", example: "Make a wish.", note: "Mong ước" },
  { word: "Help", pos: "Verb", meaning: "Giúp đỡ", example: "Need your help.", note: "Hỗ trợ" },
  { word: "Need", pos: "Verb", meaning: "Cần", example: "I need time.", note: "Thiết yếu" },
  { word: "Keep", pos: "Verb", meaning: "Giữ", example: "Keep it safe.", note: "Duy trì" },
  { word: "Start", pos: "Verb", meaning: "Bắt đầu", example: "Start now.", note: "Khởi tạo" },
  { word: "Stop", pos: "Verb", meaning: "Dừng lại", example: "Stop here.", note: "Kết thúc" },
  { word: "Begin", pos: "Verb", meaning: "Bắt đầu", example: "Let's begin.", note: "Giống start" },
  { word: "End", pos: "Verb/Noun", meaning: "Kết thúc", example: "The end.", note: "Chấm dứt" },
  { word: "Live", pos: "Verb", meaning: "Sống", example: "Live in a city.", note: "Sinh sống" },
  { word: "Die", pos: "Verb", meaning: "Chết", example: "Flowers die.", note: "Kết thúc sống" },
  { word: "Change", pos: "Verb", meaning: "Thay đổi", example: "Change your mind.", note: "Đổi khác" },
  { word: "Wait", pos: "Verb", meaning: "Chờ đợi", example: "Wait for me.", note: "Kỳ vọng" },
  { word: "Happen", pos: "Verb", meaning: "Xảy ra", example: "What happened?", note: "Diễn biến" },
  { word: "Create", pos: "Verb", meaning: "Tạo ra", example: "Create a plan.", note: "Làm mới" },
  { word: "Include", pos: "Verb", meaning: "Bao gồm", example: "Tax included.", note: "Bên trong" },
  { word: "Provide", pos: "Verb", meaning: "Cung cấp", example: "Provide support.", note: "Đưa cho" },
  { word: "Remember", pos: "Verb", meaning: "Nhớ", example: "Remember me.", note: "Ký ức" },
  { word: "Forget", pos: "Verb", meaning: "Quên", example: "Forget the past.", note: "Mất ký ức" },
  { word: "Understand", pos: "Verb", meaning: "Hiểu", example: "I understand.", note: "Nhận biết" },
  { word: "Believe", pos: "Verb", meaning: "Tin tưởng", example: "Believe in yourself.", note: "Lòng tin" },
  { word: "Agree", pos: "Verb", meaning: "Đồng ý", example: "I agree with you.", note: "Tán thành" },
  { word: "Build", pos: "Verb", meaning: "Xây dựng", example: "Build a house.", note: "Tạo dựng" },
  { word: "Fall", pos: "Verb", meaning: "Ngã / Rơi", example: "Fall down.", note: "Mất thăng bằng" },
  { word: "Cut", pos: "Verb", meaning: "Cắt", example: "Cut the paper.", note: "Cắt đứt" },
  { word: "Draw", pos: "Verb", meaning: "Vẽ", example: "Draw a picture.", note: "Nghệ thuật" },
  { word: "Grow", pos: "Verb", meaning: "Lớn lên, phát triển", example: "Plants grow.", note: "Sinh trưởng" },
  { word: "Win", pos: "Verb", meaning: "Thắng", example: "Win the game.", note: "Chiến thắng" },
  { word: "Lose", pos: "Verb", meaning: "Thua, mất", example: "Lose money.", note: "Thất bại, đánh mất" },
  { word: "Meet", pos: "Verb", meaning: "Gặp gỡ", example: "Meet my friend.", note: "Giao tiếp" },
  { word: "Send", pos: "Verb", meaning: "Gửi", example: "Send an email.", note: "Gửi đi" },
  { word: "Spend", pos: "Verb", meaning: "Dành, tiêu (tiền, t.gian)", example: "Spend time.", note: "Sử dụng tài nguyên" },
  { word: "Bring", pos: "Verb", meaning: "Mang lại", example: "Bring it here.", note: "Di chuyển đến" },
  { word: "Show", pos: "Verb", meaning: "Cho xem", example: "Show me how.", note: "Trình diễn" },
  { word: "Teach", pos: "Verb", meaning: "Dạy bảo", example: "Teach a lesson.", note: "Chỉ bảo" },
  { word: "Buy", pos: "Verb", meaning: "Mua vào", example: "Buy new shoes.", note: "Shopping" },
  { word: "Let", pos: "Verb", meaning: "Để cho", example: "Let it go.", note: "Cho phép" },
  { word: "Put", pos: "Verb", meaning: "Đặt, để", example: "Put it down.", note: "Chuyển chỗ" },
  { word: "Catch", pos: "Verb", meaning: "Bắt lấy", example: "Catch the ball.", note: "Nắm bắt" },
  { word: "Choose", pos: "Verb", meaning: "Lựa chọn", example: "Choose one.", note: "Tuyển chọn" },
  { word: "Decide", pos: "Verb", meaning: "Quyết định", example: "Decide to go.", note: "Đưa ra ý kiến" },
  { word: "Explain", pos: "Verb", meaning: "Giải thích", example: "Explain the rules.", note: "Diễn giải" },
  { word: "Improve", pos: "Verb", meaning: "Cải thiện", example: "Improve skills.", note: "Làm tốt hơn" },
  { word: "Focus", pos: "Verb", meaning: "Tập trung", example: "Focus on task.", note: "Chú tâm" },
  { word: "Suggest", pos: "Verb", meaning: "Gợi ý", example: "I suggest that...", note: "Đề xuất" },
  { word: "Solve", pos: "Verb", meaning: "Giải quyết", example: "Solve a problem.", note: "Tìm đáp án" },
  { word: "Protect", pos: "Verb", meaning: "Bảo vệ", example: "Protect nature.", note: "Che chở" },
  { word: "Relax", pos: "Verb", meaning: "Thư giãn", example: "Time to relax.", note: "Nghỉ ngơi" },
  { word: "Action", pos: "Noun", meaning: "Hành động", example: "Take action.", note: "Việc làm" },
  { word: "Activity", pos: "Noun", meaning: "Hoạt động", example: "School activity.", note: "Nhiều người tham gia" },
  { word: "Answer", pos: "Noun", meaning: "Câu trả lời", example: "Right answer.", note: "Đáp án" },
  { word: "Question", pos: "Noun", meaning: "Câu hỏi", example: "Ask a question.", note: "Hỏi đáp" },
  { word: "Reason", pos: "Noun", meaning: "Lý do", example: "The main reason.", note: "Nguyên nhân" },
  { word: "System", pos: "Noun", meaning: "Hệ thống", example: "Education system.", note: "Tổ chức" },
  { word: "Type", pos: "Noun", meaning: "Loại, kiểu", example: "Different type.", note: "Phân loại" },
  { word: "Way", pos: "Noun", meaning: "Cách, đường", example: "This way.", note: "Phương pháp / Hướng" },
  { word: "Word", pos: "Noun", meaning: "Từ", example: "A new word.", note: "Ngôn ngữ" },
  { word: "Art", pos: "Noun", meaning: "Nghệ thuật", example: "Modern art.", note: "Sáng tạo" },
  { word: "Body", pos: "Noun", meaning: "Cơ thể", example: "Human body.", note: "Sinh học" },
  { word: "Business", pos: "Noun", meaning: "Kinh doanh", example: "Small business.", note: "Thương mại" },
  { word: "City", pos: "Noun", meaning: "Thành phố", example: "Beautiful city.", note: "Địa giới" },
  { word: "Community", pos: "Noun", meaning: "Cộng đồng", example: "Local community.", note: "Nhóm người" },
  { word: "Face", pos: "Noun", meaning: "Gương mặt", example: "Pretty face.", note: "Ngoại hình" },
  { word: "Game", pos: "Noun", meaning: "Trò chơi", example: "Video game.", note: "Giải trí" },
  { word: "Group", pos: "Noun", meaning: "Nhóm", example: "Study group.", note: "Nhiều người/vật" },
  { word: "History", pos: "Noun", meaning: "Lịch sử", example: "History book.", note: "Quá khứ" },
  { word: "Idea", pos: "Noun", meaning: "Ý tưởng", example: "Good idea.", note: "Suy nghĩ" },
  { word: "Information", pos: "Noun", meaning: "Thông tin", example: "More information.", note: "Dữ liệu" },
  { word: "Law", pos: "Noun", meaning: "Luật pháp", example: "Obey the law.", note: "Quy tắc xã hội" },
  { word: "Level", pos: "Noun", meaning: "Cấp độ", example: "High level.", note: "Tiêu chuẩn" },
  { word: "Market", pos: "Noun", meaning: "Thị trường, chợ", example: "Super market.", note: "Kinh tế" },
  { word: "Member", pos: "Noun", meaning: "Thành viên", example: "Team member.", note: "Cá nhân trong nhóm" },
  { word: "Morning", pos: "Noun", meaning: "Buổi sáng", example: "Good morning.", note: "Thời gian" },
  { word: "Night", pos: "Noun", meaning: "Buổi tối", example: "Good night.", note: "Thời gian" },
  { word: "Number", pos: "Noun", meaning: "Con số", example: "A large number.", note: "Đếm" },
  { word: "Party", pos: "Noun", meaning: "Bữa tiệc / Đảng", example: "Birthday party.", note: "Ăn mừng" },
  { word: "Person", pos: "Noun", meaning: "Người", example: "A nice person.", note: "Cá nhân" },
  { word: "Power", pos: "Noun", meaning: "Sức mạnh, quyền lực", example: "Wind power.", note: "Giá trị" },
  { word: "Result", pos: "Noun", meaning: "Kết quả", example: "Test result.", note: "Hậu quả" },
  { word: "Side", pos: "Noun", meaning: "Mặt, phía", example: "Both sides.", note: "Phương diện" },
  { word: "View", pos: "Noun", meaning: "Góc nhìn", example: "Point of view.", note: "Quan điểm" },
  { word: "Voice", pos: "Noun", meaning: "Giọng nói", example: "Loud voice.", note: "Âm lượng" },
  { word: "War", pos: "Noun", meaning: "Chiến tranh", example: "World war.", note: "Xung đột" },
  { word: "Above", pos: "Prep", meaning: "Bên trên", example: "Above the law.", note: "Vị trí cao hơn" },
  { word: "Across", pos: "Prep", meaning: "Ngang qua", example: "Across the river.", note: "Đi qua" },
  { word: "Behind", pos: "Prep", meaning: "Đằng sau", example: "Behind you.", note: "Vị trí sau" },
  { word: "Below", pos: "Prep", meaning: "Bên dưới", example: "Below zero.", note: "Vị trí thấp hơn" },
  { word: "Between", pos: "Prep", meaning: "Ở giữa", example: "Between us.", note: "Giữa 2 người/vật" },
  { word: "During", pos: "Prep", meaning: "Trong suốt", example: "During the class.", note: "Thời gian diễn ra" },
  { word: "Except", pos: "Prep", meaning: "Ngoại trừ", example: "All except him.", note: "Loại trừ" },
  { word: "Through", pos: "Prep", meaning: "Xuyên qua", example: "Through the door.", note: "Đi qua" },
  { word: "Toward", pos: "Prep", meaning: "Về phía", example: "Toward the end.", note: "Hướng đến" },
  { word: "Without", pos: "Prep", meaning: "Không có", example: "Without you.", note: "Thiếu thốn" },
  { word: "Exactly", pos: "Adverb", meaning: "Chính xác", example: "Exactly right.", note: "Đồng thuận" },
  { word: "Especially", pos: "Adverb", meaning: "Đặc biệt là", example: "Especially him.", note: "Nhấn mạnh" },
  { word: "Eventually", pos: "Adverb", meaning: "Cuối cùng thì", example: "Eventually he won.", note: "Kết quả sau cùng" },
  { word: "Probably", pos: "Adverb", meaning: "Có thể, có lẽ", example: "Probably soon.", note: "Khả năng cao" },
  { word: "Suddenly", pos: "Adverb", meaning: "Đột nhiên", example: "Suddenly stopped.", note: "Bất ngờ" },
  { word: "Quickly", pos: "Adverb", meaning: "Nhanh chóng", example: "Run quickly.", note: "Tốc độ nhanh" },
  { word: "Slowly", pos: "Adverb", meaning: "Chậm chạp", example: "Walk slowly.", note: "Tốc độ chậm" },
  { word: "Carefully", pos: "Adverb", meaning: "Cẩn thận", example: "Drive carefully.", note: "Chú ý an toàn" },
  { word: "Beautifully", pos: "Adverb", meaning: "Đẹp đẽ", example: "Sing beautifully.", note: "Khen ngợi" },
  { word: "Easily", pos: "Adverb", meaning: "Dễ dàng", example: "Easily done.", note: "Không khó khăn" },
  { word: "Simple", pos: "Adjective", meaning: "Đơn giản", example: "Simple task.", note: "Dễ thực hiện" },
  { word: "Complex", pos: "Adjective", meaning: "Phức tạp", example: "Complex issue.", note: "Rắc rối" },
  { word: "Modern", pos: "Adjective", meaning: "Hiện đại", example: "Modern art.", note: "Mới mẻ" },
  { word: "Traditional", pos: "Adjective", meaning: "Truyền thống", example: "Traditional food.", note: "Cổ xưa" },
  { word: "Natural", pos: "Adjective", meaning: "Tự nhiên", example: "Natural beauty.", note: "Không nhân tạo" },
  { word: "Popular", pos: "Adjective", meaning: "Phổ biến", example: "Popular song.", note: "Được yêu thích" },
  { word: "Useful", pos: "Adjective", meaning: "Hữu ích", example: "Useful tip.", note: "Có tác dụng" },
  { word: "Danger", pos: "Noun", meaning: "Nguy hiểm", example: "In danger.", note: "Rủi ro" },
  { word: "Safe", pos: "Adjective", meaning: "An toàn", example: "Stay safe.", note: "Không nguy hiểm" },
  { word: "Happy", pos: "Adjective", meaning: "Hạnh phúc", example: "Happy life.", note: "Cảm xúc tốt" }
];
